### ISSUE TITLE
re: emojiWeather

### ISSUE THREAD

**Issue by BenLeggiero** [matryer/bitbar-plugins#1009]
FAO: (@Chandler-Davidson)

Crashes on install/firstrun:

```Log
/Users/benleggiero/BitBar\ Plugins/emojiWeather.30m.js
module.js:529
    throw err;
    ^

Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/benleggiero/BitBar Plugins/emojiWeather.30m.js:14:15)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
```

**Comment by tresni** [comment]
Hi @BenLeggiero , make sure you've installed the node.js module into the correct location. Generally you want something like `npm install -g request` (`-g` says you want it globally installed)

No scripts install their dependancies for you.

**Comment by BenLeggiero** [comment]
Node.js module??  https://getbitbar.com says nothing about this, nor [the page for emojiWeather](https://getbitbar.com/plugins/Weather/emojiWeather.30m.js)

**Comment by tresni** [comment]
Plugins can and do have dependancies of their own.  Both of the plugins you are commenting on here do.  For security reasons, we have not (and to my knowledge have no plans on) automatically installed dependancies.  We leave it up to the plugin user to research the plugin, determine the dependancies (though they are called out in the metadata), and make sure their system is properly configured.

**Comment by BenLeggiero** [comment]
Sure, but... nothing in any of the documentation, runtime, installation, or setup say anything about any dependencies or how to resolve them... I'm just supposed to know?

And this is supposed to be a product for end users? Like, I heard non-programmers talking about this on a podcast...
