### ISSUE TITLE
re: Weather Underground

### ISSUE THREAD

**Issue by BenLeggiero** [matryer/bitbar-plugins#1010]
FAO: (@asnodgrass)

Crashes on install/firstrun

```Log
/Users/benleggiero/BitBar\ Plugins/Wunderground.30m.rb
Traceback (most recent call last):
	2: from /Users/benleggiero/BitBar Plugins/Wunderground.30m.rb:3:in `<main>'
	1: from /usr/local/Cellar/ruby/2.5.0_2/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/local/Cellar/ruby/2.5.0_2/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- wunderground (LoadError)
```

**Comment by tresni** [comment]
Hi @BenLeggiero , make sure you've installed the ruby gem into the correct location.  Bitbar can not use Homebrew, Ports, or other installed interpreters without updating the first line shebang.

In this case, make sure you've done a `gem install wunderground` for Homebrew or `sudo /usr/bin/gem install wunderground` for system default ruby.

**Comment by BenLeggiero** [comment]
Ruby gem? I'm not sure what you're talking about... I got BitBar from https://getbitbar.com and I got the plugin from https://getbitbar.com/plugins/Weather. Neither of these said anything about any Ruby gems.
