### ISSUE TITLE
re: Simple RSS reader

### ISSUE THREAD

**Issue by gopo75** [matryer/bitbar-plugins#1014]
FAO: (@alesf) hi there... where are the rss feeds from?

Thx!

**Comment by gingerbeardman** [comment]
You define the feed yourself inside the plugin

```php
define('FEED_URL', 'http://feedpress.me/sixcolors?type=xml');
define('ITEM_LIMIT', 25);
```

**Comment by gopo75** [comment]
Thx a lot! For feedly?

**Comment by gingerbeardman** [comment]
Sure, how to find your URL is shown here: https://feedly.uservoice.com/knowledgebase/articles/206805-what-is-my-feed-url

**Comment by gopo75** [comment]
cheers!
