### ISSUE TITLE
re: Jenkins All Build Status

### ISSUE THREAD

**Issue by RishabhTayal** [matryer/bitbar-plugins#1015]
FAO: (@drassi)

Getting error: 

<img width="655" alt="screenshot 2018-05-06 10 50 57" src="https://user-images.githubusercontent.com/2100166/39675067-62b4e99e-511b-11e8-8226-f9a3f010808d.png">

**Comment by gingerbeardman** [comment]
You need to install python `requests` module.

**Comment by RishabhTayal** [comment]
Could you give an example of how to install those dependencies?

**Comment by drassi** [comment]
pip install requests

**Comment by RishabhTayal** [comment]
@drassi I ran `pip install requests`. The installation was successful. However I am still getting error in the plugin.

![screenshot 2018-05-07 09 42 24](https://user-images.githubusercontent.com/2100166/39707817-151c7a74-51db-11e8-90d2-0ea5dbc100d7.png)

![screenshot 2018-05-07 09 42 39](https://user-images.githubusercontent.com/2100166/39707813-1206922a-51db-11e8-9226-b09af628dbfe.png)

**Comment by gingerbeardman** [comment]
What is the default version of python on your system? 2.7 or something else?

**Comment by RishabhTayal** [comment]
`Python 2.7.13`.

**Comment by gingerbeardman** [comment]
What does this python configuration test plugin show?

[debug.1d.py](https://github.com/matryer/bitbar-plugins/files/1981402/debug.1d.py.txt)

**Comment by RishabhTayal** [comment]
This is what it shows.

![screenshot 2018-05-07 15 41 42](https://user-images.githubusercontent.com/2100166/39724014-29055f10-520d-11e8-80b2-7de3fcf71826.png)

**Comment by gingerbeardman** [comment]
@RishabhTayal if you click that there are more items to screenshot, please

**Comment by RishabhTayal** [comment]
oops.

![screenshot 2018-05-07 15 44 17](https://user-images.githubusercontent.com/2100166/39724131-83ab2ada-520d-11e8-8630-0ca3127e56c7.png)

**Comment by gingerbeardman** [comment]
Can you try: `sudo pip install requests --upgrade`

**Comment by gingerbeardman** [comment]
Also what does `/usr/bin/python -V` show in Terminal?

**Comment by RishabhTayal** [comment]
This is what I got when I ran the command  `sudo pip install requests --upgrade`


![screenshot 2018-05-07 15 51 25](https://user-images.githubusercontent.com/2100166/39724480-83f3a5ac-520e-11e8-9cb8-4c4ea8a8b001.png)

`/usr/bin/python -V` shows this:

![screenshot 2018-05-07 15 52 12](https://user-images.githubusercontent.com/2100166/39724527-a12a1e12-520e-11e8-92fd-705282b44379.png)

Still getting same error.

**Comment by gingerbeardman** [comment]
OK, one more try for now.

`sudo -H pip uninstall requests`
(confirm it is uninstalled OK)

`sudo -H pip install requests`
(try plugin again, quit and reload bitbar)

**Comment by RishabhTayal** [comment]
I tried uninstalling, reinstalling. That was successful. Restarted bitbar. However the plugin is still not working.

![screenshot 2018-05-07 16 02 32](https://user-images.githubusercontent.com/2100166/39725039-22ec7746-5210-11e8-9505-022f05317533.png)

**Comment by gingerbeardman** [comment]
Really strange... I'll continue to think about it, something is not quite right with your python install.

Let us know if you see any progress.

(I get no such error and I am also running python 2.7.10)

**Comment by gingerbeardman** [comment]
Try this? http://scmquest.com/resolved-importerror-no-module-named-requests-usr-bin-python-no-module-named-pip-on-macos/

**Comment by RishabhTayal** [comment]
Should I try uninstalling and reinstalling python?

**Comment by gingerbeardman** [comment]
First try above :)

**Comment by RishabhTayal** [comment]
what does this command supposed to do?

**Comment by gingerbeardman** [comment]
it shows you which modules python sees as installed. for me:

```
Please wait a moment while I gather a list of all available modules...

__future__          aifc                html5lib            select
_ast                altgraph            http                selectors
_asyncio            antigravity         idlelib             setuptools
_bisect             argparse            idna                shelve
_blake2             array               imaplib             shlex
_bootlocale         ast                 imghdr              shutil
_bz2                asynchat            imp                 signal
_codecs             asyncio             importlib           site
_codecs_cn          asyncore            inspect             sitecustomize
_codecs_hk          atexit              io                  six
_codecs_iso2022     audioop             ipaddress           smtpd
_codecs_jp          base64              itertools           smtplib
_codecs_kr          bdb                 json                sndhdr
_codecs_tw          binascii            keyword             socket
_collections        binhex              lib2to3             socketserver
_collections_abc    bisect              linecache           sqlite3
_compat_pickle      bleach              locale              sre_compile
_compression        builtins            logging             sre_constants
_crypt              bz2                 lzma                sre_parse
_csv                cProfile            macholib            ssl
_ctypes             calendar            macpath             stat
_ctypes_test        certifi             macurl2path         statistics
_curses             cgi                 mailbox             string
_curses_panel       cgitb               mailcap             stringprep
_datetime           chardet             markdown            struct
_dbm                chunk               marshal             subprocess
_decimal            cmath               math                sunau
_dummy_thread       cmd                 mimetypes           symbol
_elementtree        code                mmap                symtable
_functools          codecs              modulefinder        sys
_gdbm               codeop              modulegraph         sysconfig
_hashlib            collections         multiprocessing     syslog
_heapq              colorsys            netrc               tabnanny
_imp                compileall          nis                 tarfile
_io                 concurrent          nntplib             telnetlib
_json               configparser        ntpath              tempfile
_locale             contextlib          nturl2path          termios
_lsprof             copy                numbers             test
_lzma               copyreg             numpy               textwrap
_markupbase         crypt               opcode              this
_md5                csv                 operator            threading
_multibytecodec     ctypes              optparse            time
_multiprocessing    curses              os                  timeit
_opcode             cv2                 parser              tkinter
_operator           datetime            pathlib             token
_osx_support        dbm                 pdb                 tokenize
_pickle             decimal             pickle              trace
_posixsubprocess    difflib             pickletools         traceback
_pydecimal          dis                 pip                 tracemalloc
_pyio               distutils           pipes               tty
_random             doctest             pkg_resources       turtle
_scproxy            dummy_threading     pkgutil             turtledemo
_sha1               easy_install        platform            types
_sha256             email               plistlib            typing
_sha3               encodings           poplib              unicodedata
_sha512             ensurepip           posix               unittest
_signal             enum                posixpath           urllib
_sitebuiltins       errno               pprint              urllib3
_socket             faulthandler        profile             uu
_sqlite3            fcntl               pstats              uuid
_sre                filecmp             pty                 venv
_ssl                fileinput           pwd                 warnings
_stat               fnmatch             py2app              wave
_string             fontTools           py_compile          weakref
_strptime           formatter           pyclbr              webbrowser
_struct             fractions           pydoc               werkzeug
_symtable           ftplib              pydoc_data          wheel
_sysconfigdata_m_darwin_darwin functools           pyexpat             wsgiref
_testbuffer         gc                  queue               xdrlib
_testcapi           genericpath         quopri              xml
_testimportmultiple getopt              random              xmlrpc
_testmultiphase     getpass             re                  xxlimited
_thread             gettext             readline            xxsubtype
_threading_local    glob                reprlib             yapf
_tkinter            grp                 requests            yapftests
_tracemalloc        gzip                resource            zipapp
_warnings           hashlib             rlcompleter         zipfile
_weakref            heapq               runpy               zipimport
_weakrefset         hmac                sched               zlib
abc                 html                secrets             

Enter any module name to get more help.  Or, type "modules spam" to search
for modules whose name or summary contain the string "spam".
```

**Comment by RishabhTayal** [comment]
```

**Comment by RishabhTayal** [comment]
@gingerbeardman Any solutions for this in mind? Should I uninstall and reinstall `python`?

**Comment by gingerbeardman** [comment]
Given that the issue is python you should try whatever you are confident doing. Poor of ideas... for now

**Comment by joshstrange** [comment]
Ok, I noticed something that we have in common. We both seem to be using brew. Try replacing 

    #!/usr/bin/env python

at the top of the script with 

    #!/usr/local/bin/python

(or whatever the path to python is when you run `which python` as your user)
I think bitbar was getting a different python than running it from the cli (which worked for me)

**Comment by RishabhTayal** [comment]
@joshstrange That totally worked!!! That's amazing. Thanks a ton 👍

**Comment by gingerbeardman** [comment]
Interesting, what does `which python` show you? 

Rather than changing the plugin you should be able to put this in your `.bash_profile`. It would be great if we could solves this without changing the script as this will help future users.

**Comment by RishabhTayal** [comment]
`which python` shows `/usr/bin/python`. What should update in `.bash_profile`?

**Comment by gingerbeardman** [comment]
I'm not by my Mac right now, but take a look here: https://stackoverflow.com/a/5546147

**Comment by tresni** [comment]
The problem is that OSX applications don't properly honor `$PATH` set anywhere for non-terminal sessions.  (See matryer/bitbar#36 for the first known report of this for bitbar.  It's been around a while, there's an openradar on it but I can't find it from a quick google.)  So the answer is generally to update the plugin to use the path you need.
