### ISSUE TITLE
re: GitHub Notifications

### ISSUE THREAD

**Issue by RishabhTayal** [matryer/bitbar-plugins#1017]
FAO: (@flesch)

I have added the GitHub personal access token in the `.py` file. Plugin is still not showing in the menu bar.

**Comment by gingerbeardman** [comment]
Do you currently have any notifications waiting to be read? 

If there are no notifications then this plugin will not appear.

**Comment by RishabhTayal** [comment]
Ahh. I see. I did not have any notifications. When added the above comment, I saw the notification in the menu bar. 😄
