### ISSUE TITLE
re: Bitbucket Server (Stash) Pull Requests

### ISSUE THREAD

**Issue by RishabhTayal** [matryer/bitbar-plugins#1027]
FAO: (@asnodgrass)

Getting error:

![screenshot 2018-05-18 13 24 13](https://user-images.githubusercontent.com/2100166/40251382-c664a862-5a9e-11e8-900e-426fa5a0d220.png)

I have tried `sudo gem install duration` and `gem install duration`.

**Comment by RishabhTayal** [comment]
Does anyone know how to resolve this issue?

**Comment by tresni** [comment]
Are you using rbenv, rvm, or similar products? If so make sure you are using the system version of ruby when you attempt the gem install.

**Comment by RishabhTayal** [comment]
How can I check if what I am using? Not a ruby expert.

**Comment by RishabhTayal** [comment]
@tresni I believe I am using `rvm`. how can I use the system version of ruby when installing gem?

**Comment by tresni** [comment]
I don't use `rvm` myself, but I believe it's the following:

```sh
rvm use system
sudo gem install duration
```

See if that works.

**Comment by RishabhTayal** [comment]
@tresni Thanks for the suggestion, however I am still seeing the same error.

![screenshot 2018-05-22 11 39 46](https://user-images.githubusercontent.com/2100166/40376793-e5e89720-5db4-11e8-8f43-4b1b2eae0907.png)

**Comment by RishabhTayal** [comment]
@tresni I found the solution in your [comment](https://github.com/matryer/bitbar-plugins/issues/1010#issuecomment-384001563) made in other issue. 👍
