### ISSUE TITLE
re: Currency Tracker Transferwise

### ISSUE THREAD

**Issue by umutakparlar** [matryer/bitbar-plugins#1034]
FAO: (@andrewzk)

Hi, 

Cannot set refresh rate issue

How can we set currency refresh rate to 1 second ..? 

Thanks

**Comment by gingerbeardman** [comment]
The filename dictates the refresh period. I wouldn't advise a 1s refresh though

**Comment by umutakparlar** [comment]
Is there any way to make it realtime..?

**Comment by gingerbeardman** [comment]
What is realtime?

You can set bitbar to `currencylayer.1s.php` and this will give you roughly 1s intervals.

You need to check that your feed is realtime via the method you are using for getting the data.

Here is a currency ticker
```
#!/usr/bin/env php
<?php

$json = file_get_contents('http://apilayer.net/api/live?access_key=APIKEY&currencies=GBP&format=1');
echo json_decode($json, true)[quotes][USDGBP];
```
