### ISSUE TITLE
re: AKAlias

### ISSUE THREAD

**Issue by carlca** [matryer/bitbar-plugins#1061]
FAO: (@irstacks)

This is what happens after installing AKAlias...

![screen shot 2018-07-04 at 01 29 42](https://user-images.githubusercontent.com/260612/42250591-e05ef9d4-7f29-11e8-85dd-d6ac6509dc05.png)

Any ideas what the problem is? Thanks!

**Comment by gingerbeardman** [comment]
The error says everything you need to know.

the file `/Users/carica/.dotfiles/bashers/aka.zh`does not exist.

You have forgotten to set the path to your own aka file:
https://github.com/matryer/bitbar-plugins/blob/master/Dev/Shell/aka.1h.sh#L31

**Comment by gingerbeardman** [comment]
I’m not the plugin author, but it line 31 clearly states: `Set your own aka.sh/.zsh/.whatever path here.`

I do think that plugins needing manual changes should be flagged somehow. Maybe in <bitbar.dependencies></bitbar.dependencies>?

**Comment by carlca** [comment]
But how was I to know that line 31 of `aka.1h.sh` was worthy of attention? 

Further inspection of that file now reveals that this plugin was not what I thought it was, anyway, and that's not "sour grapes"!
