### ISSUE TITLE
re: jira

### ISSUE THREAD

**Issue by mauriziod** [matryer/bitbar-plugins#1081]
FAO: (@ngehlert)

Looks like auth has change a while ago and the plugin is no longer addressing the new auth method supported by Atlassian, also API endpoints have changed to use a new domain. Could it be possible to get  a fresher working version?

**Comment by ngehlert** [comment]
@mauriziod currently running jira version 7.11.0 and everything works smoothly. can you specify your problems?

**Comment by mauriziod** [comment]
Thanks for the quick reply, 

I got it working now.

I was trying to authenticate using our custom url https://<mycompany>.atlassian.net but it was returning an auth error. Decided then to change my password as it had strange characters that needed scape and finally removed the --insecure setting from curl.
