### ISSUE TITLE
re: Syncthing

### ISSUE THREAD

**Issue by franz-josef-kaiser** [matryer/bitbar-plugins#1089]
FAO: (@blockloop)

There's a newer version (0.3) available, than in this repo. Please update.

------

@matryer  The current setup for plugins is a bit strange. There's no real update mechanism aside from pinging authors. Maybe this could be changed to a single repo per plugin basis. Or Git Submodules (not preferable as it's error prone and complicated). Or some other (automated) mechanism via Build pipelines and CI/CD services like CircleCI where the author keeps his own repo as `dev`, while the CI service pushes to a `prod`/`master` branch here as second upstream as well.

**Comment by blockloop** [comment]
Where is version 0.3?

**Comment by franz-josef-kaiser** [comment]
I thought [it's here](https://github.com/sebw/bitbar-plugins/blob/bbcf98a97fcb449583566746a7f657202eeae5b5/plugin_folder/syncthing.10m.py#L4), but it seems that this is a different plugin. My mistake!

**Comment by blockloop** [comment]
Haha no worries 😉   
  
  
  
>   
>   
>
