### ISSUE TITLE
The API http://api.fixer.io is deprecated

### ISSUE THREAD

**Issue by Alexander-Serov** [matryer/bitbar-plugins#1097]
FAO: (@maxoumime)

Here is the error message: 

{
  "0": "#################################################################################################################################",
  "1": "#                                                                                                                               #",
  "2": "# IMPORTANT - PLEASE UPDATE YOUR API ENDPOINT                                                                                   #",
  "3": "#                                                                                                                               #",
  "4": "# This API endpoint is deprecated and has now been shut down. To keep using the Fixer API, please update your integration       #",
  "5": "# to use the new Fixer API endpoint, designed as a simple drop-in replacement.                                                  #",
  "6": "# You will be required to create an account at https://fixer.io and obtain an API access key.                                   #",
  "7": "#                                                                                                                               #",
  "8": "# For more information on how to upgrade please visit our Github Tutorial at: https://github.com/fixerAPI/fixer#readme          #",
  "9": "#                                                                                                                               #",
  "a": "#################################################################################################################################"
}

**Comment by maxoumime** [comment]
Arf, I used fixer.io because it didn't require an account.

**Comment by kblum** [comment]
I have created a pull request (#1114) to switch to exchangeratesapi.io which offers compatibility with the fixer.io API.
