### ISSUE TITLE
WHERE are the plugins?

### ISSUE THREAD

**Issue by gitgetgot** [matryer/bitbar-plugins#1106]
Well,
it says "View plugins" on the Website https://getbitbar.com but nothing is shown, when I click on the link. the link just goes to the Website itself.

So, when I browse to https://github.com/matryer/bitbar-plugins
I see a lot of folders with a lot of files in it. 
Does that mean, each file is a plugin and I can download it and put it into my plugin-folder? (regardless of the extension? Which indicates Ruby or Python, which I don't have on my Mac OSX)

Thank you for helping.

**Comment by gingerbeardman** [comment]
https://getbitbar.com

Plugin categories are down the left side
Search field is useful also
Click "Add to BitBar" on website to easily install

GitHub storage is not meant for users to install plugins
