### ISSUE TITLE
re: GitHub Zen

### ISSUE THREAD

**Issue by melgu** [matryer/bitbar-plugins#1109]
FAO: (@andjosh)
It doesn't work, but gives a bunch of errors instead.
<img width="835" alt="bildschirmfoto 2018-10-09 um 07 33 00" src="https://user-images.githubusercontent.com/9601403/46648499-ac889d00-cb95-11e8-9a17-30d054a77ace.png">

**Comment by andjosh** [comment]
GitHub now requires an API token to call this endpoint. All you need to do is set an environment variable of `GITHUB_TOKEN`: https://github.com/matryer/bitbar-plugins/blob/master/Lifestyle/githubzen.1m.py#L15
