### ISSUE TITLE
Clickable bash

### ISSUE THREAD

**Issue by djquazzi** [matryer/bitbar-plugins#1129]
Hi

How would I make an option clickable with a bash script?
I have this:
```
echo "Check Logs"
open /Library/Logs/Update.log
```

This opens the log on initial click of the menubar

Thanks

**Comment by gingerbeardman** [comment]
Check out this plugins as a similar example: https://github.com/matryer/bitbar-plugins/blob/master/System/deleteVSCodeTemp.sh

**Comment by djquazzi** [comment]
Thanks, Im 99% there. Im effectively trying to launch an app. (Log file in Console).
This is what I have: (I've tried many, many different ways, one line, concatenated, additional params, etc)

`#Open Log
www=("file://")
space=(" ")
launch=("open")
file=("/Library/Logs/Update.log")
full=("$launch$space$www$file")
echo "Check Logs | bash=$full"`

If you echo out the `$full` in the terminal you get 
`open /Library/Managed\ Installs/Logs/ManagedSoftwareUpdate.log`
But when run with the menubar app, it appears to only echo `open` and that's it.
Im assuming it's way the bash API that not 100%?
