### ISSUE TITLE
re: Battery remaining (Python)

### ISSUE THREAD

**Issue by wayferer** [matryer/bitbar-plugins#1130]
FAO: (@eripa)

I needed to add the following to the top of the file get things working right:

`#!/usr/bin/env PYTHONIOENCODING=UTF-8 /usr/local/bin/python3`

via https://github.com/matryer/bitbar/issues/141#issuecomment-171773836

Also, in order to get the interval to show correctly, I had to change:

`refresh_interval = sys.argv[0].split('.')[2]`

to:

`refresh_interval = sys.argv[0].split('.')[1]`

**Comment by sebasrp** [comment]
this issue can be closed since the PR #1314  was merged
