### ISSUE TITLE
Is it possible to do not show "Updating..." text in the Menu Bar if a script of plugin executes too long?

### ISSUE THREAD

**Issue by alekseysotnikov** [matryer/bitbar-plugins#1150]
Hi there! 
Is it possible to do not show "Updating..." text in the Menu Bar if a script of plugin executes too long?

**Comment by notiv-nt** [comment]
It looks like it depends on the plugin.
I dont see any `updates` only `...`

**Comment by alekseysotnikov** [comment]
> Or https://github.com/matryer/bitbar/blob/master/App/BitBar/ExecutablePlugin.m#L63 ?
Yes, this one. Does it possible to change or remove the text somehow from the plugin environment?

**Comment by gingerbeardman** [comment]
@alekseysotnikov yes, you can edit the plugin output freely. Just open the plugin in a text editor

**Comment by alekseysotnikov** [comment]
> @alekseysotnikov you'd need to build your own version of BitBar

Yeah, but I would like my plugin to work for everybody the same. Not only for me. 
You know, when this text appears, all icons from the left side moves left and after that right. It creates unnecessary movements in the menu bar. And maybe even irritable.

**Comment by alekseysotnikov** [comment]
It looks as follows ![bitbar](https://user-images.githubusercontent.com/1889355/52477738-989d8800-2bd5-11e9-8977-6f19d661b509.gif)

**Comment by gingerbeardman** [comment]
You can change it and submit a PR so everybody will get it. 

But I think there's more work needed to get rid of any movement during update.

**Comment by euf** [comment]
Is there any chance that deleting the line https://github.com/matryer/bitbar/blob/master/App/BitBar/ExecutablePlugin.m#L63 will do the trick?

**Comment by gingerbeardman** [comment]
@euf you cannot delete it IIRC, but in my personal build I changed to a space character.

**Comment by gingerbeardman** [comment]
See https://github.com/matryer/bitbar/issues/545 and follow the trail from there @euf

**Comment by euf** [comment]
Thanks!
