### ISSUE TITLE
re: Clock with calendar 

### ISSUE THREAD

**Issue by imtdeepak** [matryer/bitbar-plugins#1159]
FAO: (@WeibingChen17)
Last Month year and calendar is coming up incorrectly. Looks like only month is considered for last month and year is ignored. That's why for Jan 2019. Last month is showing as Dec 2019 instead of Dec 2018. 
![screen shot 2019-01-03 at 11 59 43 am](https://user-images.githubusercontent.com/4075252/50658906-b11fe000-0f4f-11e9-80c8-6b048521b2d4.png)

**Comment by WeibingChen17** [comment]
It has been fixed. I will request a PR. Thanks for your feedback!

**Comment by imtdeepak** [comment]
Looks Good now. 
Thanks
