### ISSUE TITLE
re: Yahoo Weather

### ISSUE THREAD

**Issue by imtdeepak** [matryer/bitbar-plugins#1160]
FAO: (@mgjo5899)
This is just showing Server loading.

**Comment by txusko** [comment]
It seems that Yahoo has retired query.yahooapis.com service.
https://twitter.com/ydn/status/1079785891558653952

**Comment by mgjo5899** [comment]
Sorry for the late reply guys.  https://github.com/matryer/bitbar-plugins/pull/1355 here it comes
