### ISSUE TITLE
re: ISS Pass Finder

### ISSUE THREAD

**Issue by IdlePhysicist** [matryer/bitbar-plugins#1172]
FAO: (@BrokenFlows)

Google API is no longer free and as such `$issnowl"` now is null. I am attempting a fix that would move to OpenStreetMap's Nominatim API. It does not have a `.formatted_address` but something that will suffice.

**Comment by mokuyo** [comment]
I've run into this problem too. Google allows free access to its API with reasonable limits, but I don't know how to incorporate the key into these scripted requests? Have you implemented an alternative that works? Thanks.
<img width="355" alt="image" src="https://user-images.githubusercontent.com/30929372/91090145-a2090c80-e622-11ea-82ec-c6a1b1249c6c.png">

**Comment by IdlePhysicist** [comment]
Wow I never thought anyone was going to look at this issue, so I don't remember if I ever implemented a fix for this. And I no longer use Bitbar because I found it hogged a *lot* of resources.

**Comment by mokuyo** [comment]
Thanks for the reply. I realized you are right about Google's API key. It's free to use for a limited number of map calls, but not for the Geocoding API which is needed here. Figured I'd give it a trial at $5/mo. Just need to specify https and the key to get the call working.

**Comment by IdlePhysicist** [comment]
Good luck! I think I will close out this issue though, since if you do produce a fix you'll probably need to submit a new plugin rather than a PR as @BrokenFlows hasn't gotten to this in the 18 months that it's been open.
