### ISSUE TITLE
re: Feedly

### ISSUE THREAD

**Issue by jiayuan** [matryer/bitbar-plugins#1223]
FAO: (@morizyun)

In the source code found at https://getbitbar.com/plugins/Web/Feedly/feedly.rb it has a reference to
https://blog.morizyun.com/posts/feedly-feed-api-script-bitbar which is pointing to a 404.

I did a search at your blog and landed on https://blog.morizyun.com/blog/feedly-feed-api-script-bitbar/index.html which is loaded. Perhaps you may want to update the link in the source code.

**Comment by morizyun** [comment]
@jiayuan Thank you very much. I fixed the link in PR https://github.com/matryer/bitbar-plugins/pull/1224 . Thank you for your kindness!
