### ISSUE TITLE
re: Weather

### ISSUE THREAD

**Issue by eboye** [matryer/bitbar-plugins#1231]
FAO: (@seripap)

Can you make it so that we can manually set the lat,lng?

ipinfo.io gives wrong city to me and CoreLocationCLI doesn't work as I don't have WiFi

Basically I've mocked up the code like this:

```
def mac_location_lookup():
  return { "loc": "45.2526331,19.7817785", "preformatted": "Novi Sad" }
```

so it could be cool if it's in variable for other users ;)

**Comment by seripap** [comment]
hey @eboye, it's been a few years since i've touched this script, but it seems like you've got a workaround. Feel free to send a PR if you'd like to see this represented. Cheers

**Comment by eboye** [comment]
Thanks for the reply. I've made the PR ;)

https://github.com/matryer/bitbar-plugins/pull/1232
