### ISSUE TITLE
re: Your time on earth How Does It Know?

### ISSUE THREAD

**Issue by msadesign** [matryer/bitbar-plugins#1234]
FAO: (@timlapluie)How does this little app know how long I have lived? It's wrong, incidentally; number should be 25,000+ days. But I don't see a pref?

**Comment by gingerbeardman** [comment]
I assume you need to edit the plugin script to refer to your birth date

**Comment by timlapluie** [comment]
@msadesign you can just change the birthday here: 
https://github.com/matryer/bitbar-plugins/blob/master/Lifestyle/time_on_earth.10m.rb#L17

**Comment by msadesign** [comment]
Got it and thanks!
