### ISSUE TITLE
re: Battery Apple Bluetooth keyboard - warning icon

### ISSUE THREAD

**Issue by borgendorf** [matryer/bitbar-plugins#1236]
FAO: (@alexandregz)
I just started using BitBar yesterday and noticed that while the keyboard and trackpad system profiler show the correct percentage (many others I tried don't), they also always show the warning icon. I don't know enough about Ruby or BitBar to figure out why. Thanks!
<img width="578" alt="menubar-bitbar-keyboard-trackpad" src="https://user-images.githubusercontent.com/16215584/57939787-e504fd80-787f-11e9-815b-b9c764e76796.png">

**Comment by gingerbeardman** [comment]
The warning icon is from bitbar that there is a problem with this plugin.

It should display like this:

![http://i.imgur.com/1FlcPYx.png](http://i.imgur.com/1FlcPYx.png)

**Comment by gingerbeardman** [comment]
Have you made the script executable?

`chmod +x keyboard-system_profiler.1m.rb`
