### ISSUE TITLE
re: Realtime Stock Tracker

### ISSUE THREAD

**Issue by cyclism6486** [matryer/bitbar-plugins#1252]
FAO: (@bogdan1304)

The stock tracker is now throwing errors:  Last one is HTTP Error: 403 Forbidden.

**Comment by rkanter** [comment]
Hi!

I had the same issue and made an updated version with their new API.  It got merged in two days ago, so if you switch to that one, it should work.
#1251

**Comment by cyclism6486** [comment]
How do I "switch to it"?  When I go to the Stock Tracker webpage and click the "add to BitBar" button I get a "Download failed" error.

**Comment by cyclism6486** [comment]
I can’t find a new version now.  When I go to the old link it gives me a download error and says the URL can’t be found.  Any pointers on how I can get the new version installed?

**Comment by gingerbeardman** [comment]
Here it is: https://getbitbar.com/plugins/Finance/stock-ticker.30s.py

There was a name change of the plugin

**Comment by cyclism6486** [comment]
Thanks - between the name change and needing to get tokens - it is now working again!
