### ISSUE TITLE
re: RBC Stock/Currency tracker

### ISSUE THREAD

**Issue by dmschulman** [matryer/bitbar-plugins#1260]
FAO: (@schmooser) it seems like the plugin can no longer query iextrading.com, error 403 Forbidden
![Screen Shot 2019-06-24 at 9 06 52 AM](https://user-images.githubusercontent.com/728454/60021237-a2dd9180-965f-11e9-813b-d13fa602300e.png)

**Comment by gingerbeardman** [comment]
Too many queries? Try again from a different IP or wait a while?

**Comment by dmschulman** [comment]
Thanks for your response, the error has been persistent for the last 2 weeks (or so) for me.

It looks like IEX began to sunset their 1.0 API as of June 1, 2019. The API has moved to a new cloud-based platform, IEX Cloud: https://iextrading.com/developer/

Querying the data now requires a developer account and access token it seems. More info on migrating can be found here: https://intercom.help/iexcloud/collections/1751918-migrating-to-iex-cloud-from-legacy-iex-group-api

**Comment by gingerbeardman** [comment]
But the plugin script does not use the API, instead it just scrapes directly from the web page.
