### ISSUE TITLE
re: Load Average/Temperature/Fan Speed

### ISSUE THREAD

**Issue by mozai** [matryer/bitbar-plugins#1272]
FAO: (@sevenfourk)

`/usr/local/bin/lstats : no such file or directory`

This plugin has prerequisites that are not even mentioned in [the official catalog](https://getbitbar.com/plugins/System/load_temp_fan.10s.sh)

I strongly suspect there is no place in the official catalog to mention prerequisites for any of these plugins.

**Comment by sevenfourk** [comment]
@mozai, sure, let's close that one.

**Comment by mozai** [comment]
Nevermind, I found "(requires iStats ruby gem)" in small text.
