### ISSUE TITLE
re: dnscrypt-proxy switcher

### ISSUE THREAD

**Issue by Coder84619** [matryer/bitbar-plugins#1273]
FAO: (@jedisct1)

I am unable to make the plug work on MacOS 10.14 and the latest bitbar. Bitbar launches and runs, but it does not appear to detect the .sh script in the plugin folder. The Bitbar icon changes to what appears to be female icon, but there are no menu drop downs for configuring dnscrypt.

**Comment by Coder84619** [comment]
Nevermind....the script is not compatible with hardwired ethernet connections, but does function when I am connected to a wifi network. I would suggest a different icon for the state when a hardwired network is connected (e.g. physical ethernet) but not actively connected to a wifi network. Enabling the script to work with hardwired ethernet would be great as well.

**Comment by gingerbeardman** [comment]
You can easily edit the script to do all of that
