### ISSUE TITLE
re: Stock Ticker

### ISSUE THREAD

**Issue by alex-ander-is** [matryer/bitbar-plugins#1276]
FAO: (@rkanter)
Does not work at all.

**Comment by gingerbeardman** [comment]
Did you edit the script?

> #-----------------------------------------------------------------------------
> # IMPORTANT: You will need an API Token.  Follow these steps
> # 1. Create a free account at https://iexcloud.io/cloud-login#/register/
> # 2. Select the free "START" tier
> # 3. Verify your email address
> # 4. Click "API Tokens" in the left menu
> # 5. Enter the "Publishable" Token in the quotes below (it should start with "pk_")
> api_token = ""
