### ISSUE TITLE
re: Todoist Today

### ISSUE THREAD

**Issue by andreazangheri** [matryer/bitbar-plugins#1281]
FAO: (@kobayashi)

macOS 10.14.6

Python 2 doesn't work
Python 3 doesn't work

API Key it's completely ignored.
No feedback or error arises.

"No plugins" phrase is displayed on BitBar wherever I put the .py file.

Todoist is in English.
The API key is correct.

**Comment by gingerbeardman** [comment]
I'll fix this ASAP.

**Comment by gingerbeardman** [comment]
Fixed.

Please confirm the plugin is in the correct directory and that it is marked as executable (`chmod +x todoist.1m.py`)

![Screen shot 2019-08-09 at 19 44 43](https://user-images.githubusercontent.com/49612/62801657-23f0cb00-bade-11e9-946c-13fe3825ca81.png)

**Comment by andreazangheri** [comment]
@gingerbeardman 

Failure.
Is this a limitation of the free version?

What do you mean by "correct directory"?

Screen
<img width="206" alt="Schermata 2019-08-09 alle 21 14 21" src="https://user-images.githubusercontent.com/32941768/62803509-e5add880-baea-11e9-99ae-c95274a5abad.png">

**Comment by gingerbeardman** [comment]
> Failure.
😱

> What do you mean by "correct directory"?

1. Click the "Open Plugin Folder..." menu item.
2. Finder will open a new window
3. Put your plugins in there
4. Restart BitBar

> Is this a limitation of the free version?
Free is the only version of BitBar. Fully featured it is

**Comment by andreazangheri** [comment]
> > Failure.
> 
> 😱
> 
> > What do you mean by "correct directory"?
> 
> 1. Click the "Open Plugin Folder..." menu item.
> 2. Finder will open a new window
> 3. Put your plugins in there
> 4. Restart BitBar
> 
> > Is this a limitation of the free version?
> 
> Free is the only version of BitBar. Fully featured it is

I was referring to Todoist of course.

I have no idea. I'm giving up on this.

**Comment by gingerbeardman** [comment]
I'm using the free Todoist, I signed up for an account so I could help you with this.

**Comment by andreazangheri** [comment]
> I'm using the free Todoist, I signed up for an account so I could help you with this.

Thank you for your kindness. 

But I am honestly out of idea ATM. 
Seriously can't get what's wrong.

**Comment by kobayashi** [comment]
Hi @andreazangheri ,

Can you share me the result of followings?
- the folder when you click "Open Plugin Folder"
- run the plugin script from your terminal

**Comment by andreazangheri** [comment]
> Hi @andreazangheri ,
> 
> Can you share me the result of followings?
> 
> * the folder when you click "Open Plugin Folder"
> * run the plugin script from your terminal

The folder is BitBar/ when I click "Open Plugin Folder"

/Users/andrea/Documents/BitBar/todoist.1m.py

Run the script from the terminal does nothing.

**Comment by gingerbeardman** [comment]
Are you using the updated, fixed V2 script?

https://github.com/matryer/bitbar-plugins/blob/master/Lifestyle/todoist.1m.py

**Comment by andreazangheri** [comment]
> Are you using the updated, fixed V2 script?
> 
> https://github.com/matryer/bitbar-plugins/blob/master/Lifestyle/todoist.1m.py

Yes, I do. 
By the way, the script is already updated from the site button "+ Add to bit bar".

This is the third time that I install BitBar in recent years.
I've been never able to run python scripts on it. Just shell scripts.

**Comment by andreazangheri** [comment]
The problem is probably related to my shell environment.
I use zsh oh-my-zsh.

See also #482

**Comment by gingerbeardman** [comment]
The script when run from the command line should produce lines of output like this:

![Screen shot 2019-08-10 at 12 30 36](https://user-images.githubusercontent.com/49612/62821293-aa52ee80-bb6a-11e9-877d-0cff0aec3f25.png)

As you can see it works with:
- my default python
- specific python2
- specific python3

**Comment by gingerbeardman** [comment]
It also works for me under fresh install of zsh (oh-my-zsh)

![Screen shot 2019-08-10 at 12 40 40](https://user-images.githubusercontent.com/49612/62821400-1c780300-bb6c-11e9-9e1c-34662f30c9ca.png)

**Comment by andreazangheri** [comment]
For 482 I was referring to the following one.

https://github.com/matryer/bitbar/issues/482

<img width="682" alt="Schermata 2019-08-10 alle 14 09 13" src="https://user-images.githubusercontent.com/32941768/62821704-6e735580-bb79-11e9-8d9a-7925aff08e83.png">

Doesn't work.

**Comment by gingerbeardman** [comment]
Perhaps it's not accurate to say it doesn't work, because there are no errors produced. I would say that "no output is generated".

Does it work in another shell? bash?

If so, you will need to get help from zsh community.

**Comment by andreazangheri** [comment]
Bash shell output is the same as zsh.

<img width="682" alt="Schermata 2019-08-10 alle 16 27 17" src="https://user-images.githubusercontent.com/32941768/62822979-cd41ca80-bb8b-11e9-8124-1f83c1e1440d.png">

**Comment by gingerbeardman** [comment]
Wow! In that case, I think help form python community might be more specific.

**Comment by kobayashi** [comment]
I am just wondering if you have any today's due tasks in your todoist? @andreazangheri

**Comment by andreazangheri** [comment]
@kobayashi

> Bash shell output is the same as zsh.
> 
> I currently have 4 scheduled today tasks on Todoist backend.
> 
> Thanks for your help anyway.
> 
> <img alt="Schermata 2019-08-10 alle 16 27 17" width="682" src="https://user-images.githubusercontent.com/32941768/62822979-cd41ca80-bb8b-11e9-8124-1f83c1e1440d.png">

**Comment by gingerbeardman** [comment]
Are those still scheduled for today? Now we 2 days after this thread was started.

(Sorry just need to check all the details)

Can you share how they look in Todoist? 

Plugin checks "due date"

![Screen shot 2019-08-11 at 15 09 32](https://user-images.githubusercontent.com/49612/62834883-0771a180-bc4a-11e9-9c56-3b717db06813.png)

**Comment by andreazangheri** [comment]
@gingerbeardman 

Hi.

Here's what I found out.

• It appears that only tasks without a specified time are listed on BitBar Todoist.1m.py plugin.

• Tasks with a specified time are not listed on the plugin.

Maybe is a known problem that I was not able / didn't have the time to find, is it?

As you can see only **Test Task** is listed on the menu bar.

<img width="498" alt="Schermata 2019-08-11 alle 17 27 23" src="https://user-images.githubusercontent.com/32941768/62835869-6260c400-bc5d-11e9-8afd-190826f4e7fd.png">

<img width="166" alt="Schermata 2019-08-11 alle 17 23 49" src="https://user-images.githubusercontent.com/32941768/62835811-d51d6f80-bc5c-11e9-8e64-6e39988b47b0.png">

**Comment by gingerbeardman** [comment]
Great! We have a breakthrough

I'll fix the plugin to also return items with a specified time.

YAY!

**Comment by gingerbeardman** [comment]
OK, fixed!

https://github.com/matryer/bitbar-plugins/blob/master/Lifestyle/todoist.1m.py

Any items with a specified time are now shown. ⏰

The time string is included in the output for those items, so you can easily see your deadline.

![Screen shot 2019-08-11 at 17 43 52](https://user-images.githubusercontent.com/49612/62836855-976e1600-bc5f-11e9-9d01-b94167668f54.png)
