### ISSUE TITLE
spotify.10s.sh won't pull Spotify now playing information.

### ISSUE THREAD

**Issue by xFahrenheightx** [matryer/bitbar-plugins#1296]
Accidentally hit the deny button on the popup and now I can't find out where to allow access. The plugin was working fine previously, but yesterday I got a popup asking for access and my muscle memory made me deny access. I've looked through privacy in settings and haven't found it. Any help would be appreciated.

<img width="585" alt="Screen Shot 2019-08-31 at 3 03 46 PM" src="https://user-images.githubusercontent.com/33299777/64068062-b75e7d00-cc00-11e9-97d4-d380d85ca514.png">

**Comment by gingerbeardman** [comment]
what version macOS?

In Mojave:

![Screen shot 2019-09-02 at 09 26 56](https://user-images.githubusercontent.com/49612/64100714-0c66d400-cd64-11e9-84c3-3e332e428318.png)

![Screen shot 2019-09-02 at 09 28 14](https://user-images.githubusercontent.com/49612/64100715-0d980100-cd64-11e9-8944-a32459b81c19.png)

**Comment by xFahrenheightx** [comment]
<img width="780" alt="Screen Shot 2019-09-02 at 9 16 35 PM" src="https://user-images.githubusercontent.com/33299777/64137568-048c4b80-cdc7-11e9-863a-8cb98c75a13d.png">
Nothing is showing up.
