### ISSUE TITLE
Allow add plugins from separate repositories

### ISSUE THREAD

**Issue by SebastianCzoch** [matryer/bitbar-plugins#1302]
Giving a possibility to add plugin to the list from the external GitHub repository will increase quality of plugins.

# Why?
In own repositories plugins can have own test scripts (using GitHub Actions or Travis or any other service)
Having repository with all plugins (current situation) we are not able to setup PR automated reviews/checks and also it will require review and merge commit from the owners of this repository.

Adding plugins as git submodules can help

Waiting for recommendations

**Comment by tresni** [comment]
This is just a central repo for people to easily find plugins, there is nothing that prevents you from installing plugins from wherever you want.
