### ISSUE TITLE
re: Battery remaining (Python)

### ISSUE THREAD

**Issue by iomatt512** [matryer/bitbar-plugins#1309]
FAO: (@eripa)

Hey - your refresh interval shows incorrectly. Fixed it by moving the index for split back from 2 to 1:
Was:   
` refresh_interval = sys.argv[0].split('.')[2]`
Fixed:   
` refresh_interval = sys.argv[0].split('.')[1]`

Not sure how to pull/push this back to git so dropping it in here.

**Comment by sebasrp** [comment]
this issue can be closed since the PR #1314  was merged
