### ISSUE TITLE
re: Github Contribution

### ISSUE THREAD

**Issue by bom0410** [matryer/bitbar-plugins#1356]
FAO: (@mizoR)

<img width="749" alt="Screen Shot 2020-01-13 at 11 54 50" src="https://user-images.githubusercontent.com/57971696/72230907-ba7c6780-35fb-11ea-8193-fa0e07ec3cd4.png">

I'm getting this kind of error. Can someone please help me out?

**Comment by bom0410** [comment]
new error

<img width="757" alt="Screen Shot 2020-01-13 at 12 21 23" src="https://user-images.githubusercontent.com/57971696/72231521-4479ff80-35ff-11ea-9862-2e74c67a2302.png">

**Comment by mizoR** [comment]
@bom0410 

I tried to reproduce this issue with Ruby 2.7.0 and 2.6.4, but couldn't reproduce it.

Could you tell me your ruby version?

**Comment by HYEOK999** [comment]
@mizo

I get the same error. (first snapshot)
My ver is ruby 2.3.7p456

**Comment by mizoR** [comment]
Thanks, I could reproduce it now!

Error seems to occur when `.bitbarrc` is started with no section.

```
title = "No section attribute - Title"

[github_contribution]
username = "mizoR"
```

And I created [a PR](https://github.com/matryer/bitbar-plugins/pull/1360) to fix it.

By the way, my bitbarrc is https://github.com/mizoR/dotfiles/blob/master/bitbarrc , so I didn't see an error.  If you can change your `.bitbarrc`, could you please try to modify it?  If not, please wait for merging the PR.
