### ISSUE TITLE
re: Ejector (request)

### ISSUE THREAD

**Issue by victor-moreno** [matryer/bitbar-plugins#1358]
FAO: (@carlsonorozco)
I find Ejector a great plugin. It could be even better if unmounted disks were shown and mount them as an option. 
Thanks

**Comment by gingerbeardman** [comment]
Currently the script looks through `diskutil info -all` output for Volume Mount Points, eg. paths at /Volumes/...

Unmounted disks do not have these, so the way the script creates its list of drives would need to be changed, which is quite difficult as it needs a lot more loving than just scanning for /Volumes/ text.

Adding the commands to remount is very easy.

**Comment by gingerbeardman** [comment]
I like a challenge so I've just done this!

- Unmounted disks below the mounted disks
- Clicking the Volume label will mount the disk

I also added the ability to hold Alt/Option to get the option to unmount a disk

**Comment by victor-moreno** [comment]
Thanks,
It is an impressive improvement.
I had to add quotes to param2='$mount_point' because it didn't work with volumen names with spaces (my new USB was labeled "NO NAME").

I have a more difficult challenge: encrypted disks are not mounted because you need to first find the UUD and run "diskutil coreStorage unlockVolume" and ask for the passphrase or read it from a file o keyring.

**Comment by gingerbeardman** [comment]
I've never dealt with encrypted disks, but I'll create one on an SD card and see how it goes!

Thanks for the bug report about the quotes, I'll fix that.
