### ISSUE TITLE
re: VPN Checker

### ISSUE THREAD

**Issue by ajkblue** [matryer/bitbar-plugins#136]
FAO: (@pldubouilh)
El Capitan now supports IKEv2 VPN, and with it a new interface. On line 12, instead of using `ifconfig | grep tun0` it should now use `ifconfig | egrep '(utun0)|(ipsec0)'` or `ifconfig | grep 'utun0\|ipsec0'` so it can accurately detect both types of VPN connections.

This will also need to be changed for line 14 at `ifconfig utun0 2> /dev/null | grep inet | cut -d' ' -f 2` but I couldn't quite figure out how to do that.

**Comment by pldubouilh** [comment]
I don't have an IKEv2 VPN to try out, could you have a try with [this gist](https://gist.github.com/pldubouilh/e02e59e52427b1f9ca75) and tell me if it's any good ?

Also, I just checked PPTP's working fine as it's creating an `utun0` interface.

**Comment by ajkblue** [comment]
Yes, that works with both IKEv1 and v2 VPN connections.
