### ISSUE TITLE
re: Brew Services

### ISSUE THREAD

**Issue by cblackburn-ajla** [matryer/bitbar-plugins#1379]
FAO: (@eproxus) - it seems that brew has renamed the `brew-services.rb` file to `services.rb`.  You can fix it by changing this:

```ruby
BREW_SERVICES = "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd/brew-services.rb"
```

to this:

```ruby
BREW_SERVICES = "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd/services.rb"
```

Sorry, I don't have the bandwidth to do a proper PR right now.

Cheers

**Comment by gingerbeardman** [comment]
This has already been fixed in https://github.com/matryer/bitbar-plugins/pull/1374 so you may want to download the latest version of the plugin.
