### ISSUE TITLE
[Question] Folder's choice for my plugin

### ISSUE THREAD

**Issue by katsuo11** [matryer/bitbar-plugins#138]
Hello,

I'm writing a plugin that gives Driving travel duration, distance and traffic delay to a favorite destination.
It uses Google maps APIs to fetch geolocation and travel data.

Where should I put my plugin before sending PR request?

I currently have it in Lifestyle/ in my fork. There is also Vehicle...

Quick and dirty concept from last night:
![screenshot](http://i.imgur.com/zJ4DSE1.png?1)

**Comment by matryer** [comment]
OK this is pretty genius. I think Travel?

**Comment by matryer** [comment]
You can make a new folder if it doesn't already exist. Please make sure it has all the appropriate [metadata](https://github.com/matryer/bitbar#metadata) too :)

**Comment by matryer** [comment]
... actually, can you rename `Vehicle` for `Travel` and put it in there?

**Comment by katsuo11** [comment]
Sounds good, I'll do that. Thanks :)
