### ISSUE TITLE
re: Stock Ticker

### ISSUE THREAD

**Issue by longterm** [matryer/bitbar-plugins#1398]
FAO: (@rkanter)

Is there a way to get your plugin to use the Dow Jones stock symbol, which is

^DJI

?

Thanks!

**Comment by rkanter** [comment]
It doesn't look like you can (directly) get any of the stock indexes via the API that the plugin uses.  I see a few questions about that in the API's github, but they've all been closed.  It's apparently very expensive to get that data.  They suggest using an ETF that matches the index instead (for DJI, that would be DIA, which does work).

https://github.com/iexg/IEX-API/issues/901

**Comment by longterm** [comment]
Thanks Robert; best,

Bob Patin
bob@patin.com
http://www.bobpatin.com
615-300-6260
