### ISSUE TITLE
re: Unsplash Background

### ISSUE THREAD

**Issue by Sergesouszero** [matryer/bitbar-plugins#1406]
FAO: (@iammarkoradak)
I installed Unsplah Background plugin and since then, my screen went entirely black. Apart from windows apps, and files on desktop, everything is hidden behind this black screen (Dock, wallpaper,etc.). I removed the plugin, reboot the Mac but it's still there. 

![Capture d’écran](https://user-images.githubusercontent.com/25295162/77959002-ed053a80-72a3-11ea-8b85-3fe1ac9c59a6.jpg)

**Comment by yonantan** [comment]
@Sergesouszero 
happened to me too. 
fixed by running in terminal
```bash
rm -rf ~/Library/Application\ Support/Dock/desktoppicture.db
```

**Comment by Sergesouszero** [comment]
@yonantan 
Thanks for your answer. Since I didn't know what to do, I reinstalled the os from a backup and everything is fine now.

**Comment by yonantan** [comment]
@Sergesouszero 
haha reinstalling the os always does the trick :)
hopefully my comment will help other poor souls avoid such a time-waste.
