### ISSUE TITLE
re: Weather

### ISSUE THREAD

**Issue by frakman1** [matryer/bitbar-plugins#1472]
FAO: (@seripap)

Your screenshot shows a Radar map. However, when I run mine, I don't get any map.
What am I missing?

![image](https://user-images.githubusercontent.com/5826484/89012887-ec77c180-d2e0-11ea-98ea-dfc70a946bb0.png)

**Comment by seripap** [comment]
Darksky removed that feature from their API a couple years ago so it's unfortunately no longer available.

**Comment by frakman1** [comment]
I see. Thank you for confirming.
