### ISSUE TITLE
re: clipboard-history.3s.sh

### ISSUE THREAD

**Issue by falquan** [matryer/bitbar-plugins#150]
Multi-user logins cause permission denied error. The path cannot be written by a different user than the plugin is installed.

I worked around it by including $USER environment variable as part of the tmp_dir variable:

`tmp_dir="/tmp/bitbar-clipboard-history_$USER"`

<img width="880" alt="screen shot 2016-01-18 at 3 08 55 pm" src="https://cloud.githubusercontent.com/assets/4510714/12405029/742eb170-bdf5-11e5-8792-3ea1818d150e.png">

**Comment by keithamus** [comment]
Fancy making a PR for this @falquan?

**Comment by falquan** [comment]
Done and done!
