### ISSUE TITLE
dnscrypt-proxy switcher not shown in status bar 

### ISSUE THREAD

**Issue by dfang** [matryer/bitbar-plugins#1519]
upgraded to macOS big sur, dnscrypt-proxy switcher can't load

**Comment by andromedarabbit** [comment]
```
+ sw_vers -productVersion
+ osversion=11.0.1
+ echo 11.0.1
+ awk -F. '{print $2}'
+ osmajor=0
+ [ 0 -lt 7 ]
+ exit 1
```

This might help to fix this...

**Comment by dfang** [comment]
@andromedarabbit 

https://github.com/matryer/bitbar-plugins/blob/master/Network/dnscrypt-proxy-switcher.10s.sh#L48

removing L48-L50 can solve my issue

thanks !
