### ISSUE TITLE
[Feature] - No support for buildbot

### ISSUE THREAD

**Issue by ryansydnor** [matryer/bitbar-plugins#156]
Self-explanatory - support for jenkins, travis, etc. already exists. Would love something similar for buildbot.

**Comment by matryer** [comment]
Would you like to have a stab at writing this and submitting a PR?

**Comment by ryansydnor** [comment]
Sure thing!

**Comment by tresni** [comment]
[Jenkins](https://getbitbar.com/plugins/Dev/Jenkins/jenkins-all-jobs.status.1m.py) [2](https://getbitbar.com/plugins/Dev/Jenkins/jenkins-multiple-projects-status.1m.sh) [3](https://getbitbar.com/plugins/Dev/Jenkins/jenkins-status.1m.sh), [TravisCI](https://getbitbar.com/plugins/Dev/Travis/travis-check.2m.py), [Semaphore CI](https://getbitbar.com/plugins/Dev/Semaphoreci/project-list.5m.js), and [CircleCI](https://getbitbar.com/plugins/Dev/CircleCI/circleci-check.5m.py) all have plugins contributed.  We welcome any additional plugins/pull requests :)
