### ISSUE TITLE
[Feature] - Script parameter input

### ISSUE THREAD

**Issue by ryansydnor** [matryer/bitbar-plugins#157]
I see lots of scripts with 'YOUR KEY HERE' variables towards the top. It would be awesome if bitbar allowed a user to enter their configuration through the application UI rather than by modifying a script. This feature would lower the barrier to entry for non-developer types.

**Comment by keithamus** [comment]
Hey @ryansydnor, we have a pretty active discussion about this over in https://github.com/matryer/bitbar/issues/88. I'll close this one - but you should totally check out the linked issue :smile:
