### ISSUE TITLE
Proposals for Ejector

### ISSUE THREAD

**Issue by JayBrown** [matryer/bitbar-plugins#188]
Proposals for Ejector script (ejector.5s.sh by carlsonorozco).

(1) If the volumes are mounted DMGs, you could add another menu item: "Eject all DMGs"
(would leave physical volumes mounted)

(2) Vice versa a menu item: "Eject all physical volumes"
(would leave DMGs mounted)

and maybe

(3) "Eject all physical volumes except Time Machine"
(would leave DMGs and Time Machine volume mounted)
That would be something I'd like. ;)

(4) In addition there's an app called CleanMyDrive by MacPaw, which also has a junk cleaner for .DS_Store, .Spotlight-V100, .TemporaryItems, .fseventsd (OS X) plus Thumbs.db, RECYCLED, RECYCLER, $RECYCLE.BIN (Windows) plus resource forks, i.e. ._filename.extension

That could be added too for all writable volumes except the boot volume.

**Comment by keithamus** [comment]
We welcome PRs if you fancy trying to alter this :smile: 

/cc @carlsonorozco

**Comment by carlsonorozco** [comment]
I'll try to do this. Thanks @keithamus and @JayBrown

**Comment by carlsonorozco** [comment]
@JayBrown I implemented **1 - Eject All Disk Images** and **2 - Eject All Physical Volumes**

**Comment by tresni** [comment]
Closing as I believe the requests have been met :)
