### ISSUE TITLE
re: Weather

### ISSUE THREAD

**Issue by MichaelPak** [matryer/bitbar-plugins#198]
FAO: (@seripap)

    michaelpak@macbook: /Users/michaelpak/Documents/BitBarPlugins/weather.15m.py
    Could not get weather

**Comment by MichaelPak** [comment]
I have already got `api_key`, but it still doesn't work

**Comment by MichaelPak** [comment]
I have found problem. It's in `get_wx()` in `weather_data['visibility']` and `weather_data['next_hour']`, cause `json` response from `forecast` hasn't got `['currently']['visibility']` and `['minutely']['summary']`

**Comment by seripap** [comment]
What location are you grabbing weather for? The plugin checks weather for all those nodes- if one doesn't exist it'll catch the exception and hang. You can modify it by deleting some of the nodes that may not work for specific location, or add better error-handling for each of the nodes

**Comment by MichaelPak** [comment]
That's response from `ipinfo.io`:

    {
      "ip": "212.5.****.****",
      "hostname": "firewall.****.ru",
      "city": "",
      "region": "",
      "country": "RU",
      "loc": "55.7500,37.6166",
      "org": "****"
    }

I'm from Russia/Moscow

**Comment by chakler** [comment]
I live in Manila and have the same problem as well. The JSON I got from forcast.io doesn’t provide any `minutely` information.

It’d probably be better if the less important information are conditional based on availability. :smiley:

**Comment by seripap** [comment]
I'll fix this up to be a bit more conditional for my international friends :+1:

**Comment by MichaelPak** [comment]
Thanks a lot!

**Comment by chakler** [comment]
Tried https://github.com/matryer/bitbar-plugins/pull/226. Works like a charm! Thanks!

**Comment by MichaelPak** [comment]
good work amigo!
