### ISSUE TITLE
ping.10s.sh use MAX_PING for pings >1000ms

### ISSUE THREAD

**Issue by Ths2-9Y-LqJt6** [matryer/bitbar-plugins#204]
Heya!  On line 10 we have `MAX_PING=10000` but then on on line 54 we have `if [ $AVG -ge 1000 ]; then`.  I'm on a flight now were my avg ping time is >1000 but I still want to know what it is instead of just knowing "OMG IT IS SO SLOW".  

I suggest changing line 54 to  `if [ $AVG -ge $MAX_PING ]; then` so folks like me can easily set a higher max ping so we can see it in the menu.

If you're open to a pull request, I'd be happy to do the "heavy" lifting of the one line change ;)

**Comment by etlovett** [comment]
Sounds like a good change to me, FWIW.  Right now [that if-else](https://github.com/matryer/bitbar-plugins/blob/fff89455de8e1666e104bb27916e4e93688b1e2a/Network/ping.10s.sh#L54-L67) has colors for each part of the time range up to the "dead" time of 1000ms, so we should probably keep it contiguous.  So alongside your suggestion of bumping the "dead" time to `MAX_PING`, I'd recommend introducing a new color band for when the time is between 1000ms and `MAX_PING`.

**Comment by Ths2-9Y-LqJt6** [comment]
@etlovett  - Awesome sauce!  I'll do up a PR and be in touch.  Still on my flight, so I have plenty of time as long as my bandwidth holds up ;)

@keithamus - thanks for passing my request along.

**Comment by Ths2-9Y-LqJt6** [comment]
I'm working up the PR and remember I'm not a front end guy.  I picked `#ff0101` from http://html-color-codes.info as a hot HOT red for when ping avg is between 1000 & `MAX_PING`.  I'm totally open to input on this!

**Comment by Ths2-9Y-LqJt6** [comment]
Okie dokie - matryer/bitbar-plugins#205 is ready when ever ya got a sec.

**Comment by keithamus** [comment]
Changes seemed fine to me - but if you want to make more changes feel free to open subsequent PRs :smile:

**Comment by Ths2-9Y-LqJt6** [comment]
Awesome, thanks for the merge!  My other co-workers who fly thank you ;)
