### ISSUE TITLE
re: TravisCI Check

### ISSUE THREAD

**Issue by matryer** [matryer/bitbar-plugins#274]
FAO: (@tomkinsc)

Sometimes I get this weird error (attached). Seems random.

<img width="727" alt="screen shot 2016-02-23 at 23 27 04" src="https://cloud.githubusercontent.com/assets/101659/13270297/07fa93fa-da85-11e5-89d0-89f071a418a3.png">

**Comment by tomkinsc** [comment]
Give #275 a try. Maybe a different color/symbol would make more sense?
