### ISSUE TITLE
re: CircleCI Check

### ISSUE THREAD

**Issue by welcoMattic** [matryer/bitbar-plugins#294]
FAO: (@fsegouin)

~~I catch this error after plugin installation (and `chmod +x ~/bitbar-plugins/circleci-check.5m.py` run):~~

`ImportError: No module named requests`

~~I have `requests` module installed via `pip` :~~

`$ pip list`

```
...
requests (2.9.1)
...
```

~~Any idea to solve it?~~

EDIT: initial issue is fixed. It was a mess with multiple python version on my mac. Ans with the linked PR, I just fix the missing no_tests index.

**Comment by welcoMattic** [comment]
Up:

I'm on OS X 10.11.3

**Comment by welcoMattic** [comment]
Ping @fsegouin @matryer

**Comment by tresni** [comment]
Closing as reference PRs are either merged or closed.
