### ISSUE TITLE
Weather plugin excessively calling forecast.io API?

### ISSUE THREAD

**Issue by chrisidefix** [matryer/bitbar-plugins#296]
@seripap 

Thanks for the Weather plugin - I love it even though I only used it for a few days now.
Today, however, for the first time I only see the "Could not get weather" response.

Turns out I had over 2646 API calls yesterday and already 1217 today. I have no idea how this is possible, since the plugin should only update ever 15min, but let me know how many API calls you expect per day. I expected under 100 per day, but maybe I didn't read the code right.

Could there be something forcing the plugin to keep calling the forecast.io API (let's say my connection drops out or whatever). Or should I expect someone else using my API token (I didn't publish it anywhere and am only using it for this one purpose).

If you have any thought, please let me know!

**Comment by seripap** [comment]
I'm seeing some craziness on my side as well- what version bitbar are you using? I just recently updated to v1.6 and it seems to be going wild on me as well.

<img width="204" alt="screenshot 2016-03-05 23 28 37" src="https://cloud.githubusercontent.com/assets/683200/13552300/62d7f3d2-e32a-11e5-951b-7c28fe4efbde.png">

**Comment by chrisidefix** [comment]
Wow, my english sounds terrible, when I'm in a rush - sorry about that.

Yes, I am on the latest BitBar release 1.6, but nothing seems to indicate that the plugins are called more often than what their scheduled time says. I added some simple logging, but didn't see anything out of the ordinary, yet.

Actually, my computer was asleep many of those hours in the last 48 hour period and I would have expected an even lower number of API calls. Checking the Activity Monitor I did notice that BitBar has quite a high "Average Energy Impact". That number is almost 10 x the Safari Number and exactly 10 x my main text editor and both of these applications are open all the time and I would assume are a bit more resources hungry than BitBar ?

I do have 5 Python plugins and I know that "Avg Energy Impact" calculation is probably to be taken with a grain of salt, but I wonder if BitBar plugins are still executed while the Mac is sleeping? (testing that now)

**Comment by chrisidefix** [comment]
The first thing I noticed is that BitBar will refresh all plugins as soon as you wake your Mac from sleep. It doesn't matter how much time has passed since the last refresh, it will always do another refresh. Still, this is sort of expected behaviour, as I would be surprised if my computer woke up from sleep more than 20 times a day. I wonder though, if PowerNap or something else on the computer may be able to trigger a refresh as well. Any ideas?

**Comment by chrisidefix** [comment]
Alright, I can confirm that BitBar appears to randomly refresh scripts that it is not "supposed" to. I have no idea why, but on this example the weather plugin is set to refresh every 15min. I added a log to see at which times my script would get called.

```
================ < initial plugin start 
2016-03-06 16:50:52.130957
================ < manual refresh (through BitBar) after 10 min
2016-03-06 17:00:57.696849
================ < another manual refresh after 5 min
2016-03-06 17:05:14.987406
================ < computer went to sleep - this refresh is from waking up again
2016-03-06 17:05:55.888563
================ < another manual refresh 5 min after waking up
2016-03-06 17:10:52.304677
================ < another sleep then wake test to see if BitBar refreshes again
2016-03-06 17:16:44.743760
================ < ARBITRARY refresh 3 min later
2016-03-06 17:19:22.612096
================ < another ARBITRARY refresh 3 min after that
2016-03-06 17:23:40.841455
================ < 1 min (ARBITRARY)
2016-03-06 17:24:21.550339
================ < 4 min (ARBITRARY)
2016-03-06 17:29:17.453129
================ < 2 min (ARBITRARY)
2016-03-06 17:31:52.078755
================ < 3 min (ARBITRARY)
2016-03-06 17:34:28.568005
================ < 4 min (ARBITRARY)
2016-03-06 17:38:44.807051
================ < 1 min (ARBITRARY)
2016-03-06 17:39:25.760066
================ < 5 min (ARBITRARY)
2016-03-06 17:44:21.348986
================ < 2 min (ARBITRARY)
2016-03-06 17:46:55.819093
================ < 3 min (ARBITRARY)
2016-03-06 17:49:32.878901
================ < computer woke up from sleep
2016-03-06 18:35:10.855741
```

**Comment by chrisidefix** [comment]
I believe this is clearly a BitBar Bug: https://github.com/matryer/bitbar/issues/263
