### ISSUE TITLE
get bitbar plugins up to par with istat menus

### ISSUE THREAD

**Issue by strages** [matryer/bitbar-plugins#305]
I would love to get into bitbar! Use it as a replacement for istatmenus. Hoever it is not yet on par with it. For example the cpu meter should be a detailed mini graph with more information when hovering over it as seen in the screenshot. Download upload rates should be able to be displayed as in the screen shot double lines etc. Is this doable atm with bitbar? 

<img width="452" alt="screenshot 2016-03-09 11 49 26" src="https://cloud.githubusercontent.com/assets/429659/13635133/3535a758-e5fa-11e5-8dff-063a00369b38.png">

*copy of https://github.com/matryer/bitbar/issues/264*

**Comment by keithamus** [comment]
Thanks @strages - but I'll close this and we can continue the discussion in https://github.com/matryer/bitbar/issues/264
