### ISSUE TITLE
re: Show / Edit network location - Long location names

### ISSUE THREAD

**Issue by sejtam** [matryer/bitbar-plugins#306]
FAO: (@ffittschen)

I found 2 issues with your Location plugin for bitbar

1. sometimes It does not update the display when I change the location using the top-left APPLE menu/Location

2. I have a location whose name is rather long "TM Innovation Centre". It appears in the dropdown menu as 3 separate lines, each of which ic clickable. That sounds/looks wrong...

cheers

**Comment by tresni** [comment]
Display is only updated when the plugin updates.  That's currently set to once an hour (you may modify that in by changing the plugin name and refreshing all plugins.)

The issue with 2 is the use of a `for i in $var`.  In BASH that parses on any whitespace, not newlines.  So the correct way per [BashFAQ/001](http://mywiki.wooledge.org/BashFAQ/001) is to use a `while` loop instead.

I'm bored so pushing a fix for that shortly ;-)
