### ISSUE TITLE
re: RescueTime

### ISSUE THREAD

**Issue by sfarzy** [matryer/bitbar-plugins#317]
FAO: (@kfdm)
Missing API Key
![screen shot 2016-03-16 at 18 25 47](https://cloud.githubusercontent.com/assets/10276208/13812902/97391912-eba4-11e5-84e7-ce7fc6d3055e.png)

**Comment by tresni** [comment]
Please see the comment in the plugin:

```bash
# To install, you will want to generate an API key for rescue time and then store the
# key in ~/Library/RescueTime.com/api.key
# https://www.rescuetime.com/anapi/manage
```
