### ISSUE TITLE
re: Live Cricket Scores

### ISSUE THREAD

**Issue by sfarzy** [matryer/bitbar-plugins#330]
FAO: (@anupsabraham)

Not working as intended. This is how it works.
![image](https://cloud.githubusercontent.com/assets/10276208/13881501/2789e7b4-ed47-11e5-95d5-7fc23576482f.png)

Screen shot was during the match, Scores are not updated.
Am I missing something?

**Comment by anupsabraham** [comment]
The text color is set black here. So can't see the text in dark theme. Will fix this ASAP.

**Comment by sfarzy** [comment]
Thank you @anupsabraham. Works perfectly on both Modes. Hope it'll be updated soon plugin gallery also. @matryer

## Darkmode
![image](https://cloud.githubusercontent.com/assets/10276208/13906167/17012654-eef6-11e5-9324-bbd94c0d49e8.png)

## Normal Mode
![image](https://cloud.githubusercontent.com/assets/10276208/13906170/26eec0b2-eef6-11e5-9664-d4c959538edd.png)

**Comment by anupsabraham** [comment]
:+1:
