### ISSUE TITLE
re: Todoist Today

### ISSUE THREAD

**Issue by douglance** [matryer/bitbar-plugins#358]
FAO: (@chiisaihayashi)

I put in my API Token and it's not loading! Does it require a specific version of Python? What did I do wrong? :frowning:

**Comment by chiisaihayashi** [comment]
What was the message you can see at the menu bar?

**Comment by matt-raporte** [comment]
I'm having the same issue, it doesn't seem to be returning a value at all:

Matts-MacBook-Pro:~ mraporte$ /Users/Ratt/BitBar\ Plugins/balance.1h.sh
BTC: Matts-MacBook-Pro:~ mraporte$ 

(here's where I'm finding the API key.. new at this maybe I'm using the wrong one?)
http://imgur.com/RZP4M8C

**Comment by chiisaihayashi** [comment]
matt,
As long as I check the image you attached, API key might not correct.
You can find API token at "Account" menu from settings of Todoist.

**Comment by douglance** [comment]
No messages at all. API is accurate. Language is English.

**Comment by chiisaihayashi** [comment]
I cannot re-create the issue... Could you run in terminal?

**Comment by douglance** [comment]
Doesn't work. 😢

**Comment by douglance** [comment]
>ImportError: No module named 'urllib2'

Got this error.

**Comment by douglance** [comment]
If I remove:
>if item['date_string'] == today:

The plugin is mostly functional, but it cycles through all tasks and project titles.

**Comment by douglance** [comment]
When I do this debug print statement:
```

    for item in items:
        print(today)
        print item['date_string']
```


It prints this:

> 18 May
> everyday.
> 18 May
> everyday
> 18 May
> Everyday
> 18 May
> everyday
> 18 May
> everyday.
> 18 May
> everyday
> 18 May
> Every day
> 18 May
> 
> 18 May
> every monday
> 18 May
> every second and fourth friday of the month
> 18 May
> Every thursday at 10:30AM
> 18 May
> 
> 18 May
> Jun 1
> 18 May
> 
> 18 May
> Everyday
> 18 May
> everyday
> 18 May
> every 18th of the month
> 18 May
> May 25
> 18 May
> May 25
> 18 May
> May 25
> 18 May
> May 25
> 18 May
> May 25
> 18 May
> Jun 30
> 18 May
> Jul 31
> 18 May
> 
> 18 May
> 
> 18 May
> 
> 18 May
> 
> 18 May
> May 20
> 18 May
> Jun 1
> 18 May
> every 25th
> 18 May
> every 15th
> 18 May
> every 11th
> 18 May
> every 11th
> 18 May
> every 1st
> 18 May
> every 8th
> 18 May
> every 8th
> 18 May
> every 8th
> 18 May
> every 1st
> 18 May
> 
> 18 May
> every 8th of the month
> 18 May
> every 4th of the month
> 18 May
> every 25th of the month
> 18 May
> every 1st of the month
> 18 May
> every 28th of the month
> 18 May
> every 21st of the month
> 18 May

So I don't think the strings are lining up. Is there another way to grab the items?

**Comment by chiisaihayashi** [comment]
The function is still working on my macbook...
my python ver is "2.7.11".
Here is the output on my environment.
```
$ python todoist.1m.py                                                                                                                                                               
Today's task: test
```

Could you install "urllib2"? 

```
pip install urllib2
```

**Comment by douglance** [comment]
```
Could not find a version that satisfies the requirement urllib2 (from versions: )
No matching distribution found for urllib2
```

urllib2 is apart of the standard library in Python 2.7.

**Comment by douglance** [comment]
I think the issue is that it doesn't find anything here:

`if item['date_string'] == today:
`

Because the strings don't match exactly.

**Comment by chiisaihayashi** [comment]
Thanks to your comment, I found it does not support recurring tasks. This issue will be fixed by new pr https://github.com/matryer/bitbar-plugins/pull/430 .
