### ISSUE TITLE
Netinfo Plugin

### ISSUE THREAD

**Issue by Gram21** [matryer/bitbar-plugins#373]
The Netinfo Plugin has a bug in the ipv6 curl adress. 
Line 52 should be changed form
`EXTERNAL_IP6=$(curl --connect-timeout 3 -s http://v6.ipv6-test.com/api/myip.php || echo None)`
to
`EXTERNAL_IP6=$(curl -6 --connect-timeout 3 -s http://v6.ipv6-test.com/api/myip.php || echo None)`

Otherwise the URL cannot be resolved by curl.

**Comment by q1x** [comment]
Seems to be working for me. Nevertheless, it's a good idea to force ipv6.

I'll prepare a pull request.

**Comment by q1x** [comment]
https://github.com/matryer/bitbar-plugins/pull/395
