### ISSUE TITLE
re: Pi-hole status

### ISSUE THREAD

**Issue by seanernet** [matryer/bitbar-plugins#397]
FAO: (@siimots)Hello, my PiHole is installed via the DietPi version and does not have the admin console at the typical address. My admin console is at 192.168.1.*/html/pihole/index.php Can you advise how to make the script work. Thank you.

**Comment by siimots** [comment]
Hi

I haven't tried using DietPi, but maybe you could try changing:

`# Change to Your Pi-Hole Admin Console URL`
`pihole = "http://192.168.0.101/admin/"`

to

`# Change to Your Pi-Hole Admin Console URL`
`pihole = "http://192.168.1.*/html/pihole/"`


Code needs to access api.php file:
http://192.168.1.*/html/pihole/api.php

I'm not sure if this was helpful. I can't test it using DietPi.

**Comment by seanernet** [comment]
Thank you, I'm up and running now. For some reason editing the script wouldn't get it going. I installed the plugin from the BitBar webpage and edited the single line and it's good to go. Thank you for the fast response.

**Comment by seanernet** [comment]
For anyone else with DietPi, this is my line in the script:
pihole = "http://192.168.1.88/html/pihole/"
