### ISSUE TITLE
re: Hacker News

### ISSUE THREAD

**Issue by rkumar** [matryer/bitbar-plugins#415]
FAO: (@manorie)
I get this on running Hacker News.

/Users/xxx/bitbar/hacker_news.1m.rb:32:in `initialize': No such file or directory @ rb_sysopen - /Users/xxx/hacker_news_data.txt (Errno::ENOENT)
	from /Users/xxx/bitbar/hacker_news.1m.rb:32:in `open'

I tried `touch` to create the file, but then got a `marshal data too short`. So how does one run this the first time, when the file does not exist ?

Thanks.

**Comment by manorie** [comment]
Thanks for reporting @rkumar ,
I have fixed the problem will be sending PR asap.

**Comment by rkumar** [comment]
Thanks, it is working great now.

**Comment by manorie** [comment]
you are welcome @rkumar
