### ISSUE TITLE
re: Subreddit Links

### ISSUE THREAD

**Issue by rkumar** [matryer/bitbar-plugins#416]
FAO: (@caneroj1)

When I run this, I get no data returned. The hash "data" has only one key namely "error". When i run the same URL on my browser, I do get JSON data, but using this script, and also if I run `curl https://www.reddit.com//top.json` on the command line using curl, I get "{"error": 429}% ".

**Comment by caneroj1** [comment]
I just opened pull request #418 to take care of this issue.

Error 429 was being received because our user-agent was being rate-limited. The change solves the problem for me. Let me know if it still doesn't work.

**Comment by rkumar** [comment]
Works fine, now. Thanks a lot.
