### ISSUE TITLE
re: Subreddit Links

### ISSUE THREAD

**Issue by rkumar** [matryer/bitbar-plugins#419]
FAO: (@caneroj1)

When I click on an article, the article should open in the browser. Currently, clicking just closes the dropdown list of articles. So then I do have to go to reddit on my browser and click on the article again. (You can check the Hacker News plugin, clicking the comments/score opens the comments in the browser).

Thanks for a wonderful plugin.

**Comment by caneroj1** [comment]
Well then, can't say that is happening to me. It opens fine in safari. Which browser are you using?

**Comment by rkumar** [comment]
Default is Firefox. will try with Safari and see. Thx.

**Comment by tresni** [comment]
Closing due to no further comments.
