### ISSUE TITLE
re: Hacker News

### ISSUE THREAD

**Issue by rkumar** [matryer/bitbar-plugins#420]
FAO: (@manorie)

Your plugin works fine. However, it uses an article title as the headline which obscures all my other plugins on the bitbar ! In my local copy, i have thus modified it to just print "HN" as the title.

Thanks for your good work. I like that clicking on an article opens it in the browser :)

**Comment by manorie** [comment]
Yes but in my case, I only use one plugin and want to see the titles changing every minute.
I think thats all about preference.

**Comment by dkhamsing** [comment]
There's a new support for multiple lines in beta https://github.com/matryer/bitbar/releases/tag/v2.0.0-beta4

Wonder if it's easy to add as an option 😄 

<img width="397" alt="multi" src="https://cloud.githubusercontent.com/assets/4723115/15304632/52f7ad28-1b73-11e6-9b6d-6e28dbc54420.png">
