### ISSUE TITLE
re: Taskwarrior

### ISSUE THREAD

**Issue by kfdm** [matryer/bitbar-plugins#421]
FAO: (@christophruss)
Is there a way to have it show the list with the annotations filtered out? The extra annotations from taskwarrior are making the list quite long. I looked at the code myself, but I'm pretty new to taskwarrior so I'm having difficulty understanding the correct filters I need to use for the 'next' or 'completed' list commands.

**Comment by kfdm** [comment]
Actually I guess this should be to @chrisidefix since that seems to be the author (the above looks like a github org)

**Comment by chrisidefix** [comment]
Generally, you can customise the task warrior output quite well and ask it for anything you like (https://taskwarrior.org/download/task-latest.ref.pdf).

I believe the problem with reformatting more custom output was that it wouldn't easily align and you loose other information relevant for the task (and very relevant for me to trigger actions that let you click on a task). It would become quite complex to manage custom output, so I didn't go down that path.

However, if what you are saying is that the description output is simply too long sometimes ... we can easily add a max string size to each output line and just cut off the string - would that work for you?

**Comment by kfdm** [comment]
Right, though I want to see just the issue titles, but it seems like it's pulling in the extra annotations. I use the bugwarrior ( https://github.com/ralphbean/bugwarrior ) script to sync with Github so then it's putting in a lot of extra metadata like this.

```
task next
10        5mo H gntp                                        (bw)PR#47 - Fix unicode messages .. https://github.com/kfdm/gntp/pull/47                      8.89
                                                              2015-12-08 @kfdm - Thanks for the catch. Which version of Python...                             
                                                              2015-12-08 @Ameriks - Sorry, I didn't run tests on all versions, bu...                          
                                                              2015-12-08 @kfdm - I know the Six library does a few things to c...                             
                                                              2015-12-08 @Ameriks - I'm pretty sure that this will fail, but I wa...                          
                                                              2015-12-08 @Ameriks - BTW, I didn't use six library, but instead tr...                          
34        5mo H gntp-regrowl                                (bw)PR#6 - Created bridge serve a RSS feed of  .. https://github.com/kfdm/gntp-regrowl/pull/6 8.69
                                                              2015-12-08 @kfdm - Some neat ideas in there, but it may take me ...   
```

so I'm getting some weird extra output from the BitBar plugin

```
$ ./taskwarrior.4m.py
③
---
---
ID Active Age P Project         Tag         Description                                      Urg | size=12 font=Courier
---
53 1d     5mo M django-pomodoro enhancement (bw)Is#3 - Switch to using charfields of reaso   10.6 | size=12 font=Courier color=Red refresh=true bash=/usr/bin/
53 1d     5mo M django-pomodoro enhancement (bw)Is#3 - Switch to using charfields of reaso   10.6 | size=12 font=Courier color=Red refresh=true bash=/usr/bin/
.. | size=12 font=Courier color=Red refresh=true bash=/usr/bin/python param1=./taskwarrior.4m.py param2=stop param3=.. terminal=false
.. | size=12 font=Courier color=Red refresh=true bash=/usr/bin/python param1=./taskwarrior.4m.py param2=done param3=.. terminal=false alternate=true
https://github.com/kfdm/django-pomodoro/issues/3 | size=12 font=Courier color=Red refresh=true bash=/usr/bin/python param1=./taskwarrior.4m.py param2=done par
10        5mo H gntp                        (bw)PR#47 - Fix unicode messages ..              8.89 | size=12 font=Courier color=Yellow refresh=true bash=/usr/b
https://github.com/kfdm/gntp/pull/47 | size=12 font=Courier color=Yellow refresh=true bash=/usr/bin/python param1=./taskwarrior.4m.py param2=start param3=http
2015-12-08 @kfdm - Thanks for the catch. Which | size=12 font=Courier color=Yellow refresh=true bash=/usr/bin/python param1=./taskwarrior.4m.py param2=done pa
...
```

**Comment by chrisidefix** [comment]
I don't really see anything too weird about this. It shows the task ID first, then the days active, then the age and so on. If you are referring to the trailing formatting commands (e.g. ` | size=12 font=Courier color=Red ...`) that won't actually show up in your BitBar menu bar - does it?

Apart from that I tried to explain that I need to get the task `ID` to be able to interact with the tasks - so it's not just a `task next` output. I can't interact with the tasks otherwise.

If you don't need any interaction through the menu bar or want to spend time reformatting your output - it's sort of intended with BitBar plugins that you can customise them. This is just an example for people to build upon and it won't meet everyones needs, but that's the beauty of these scripts - they are very easily edited and extended.

**Comment by kfdm** [comment]
A picture would probably be much more helpful. Sorry for not including that at first ^^; 
<img width="751" alt="2016-05-29 9 43 57" src="https://cloud.githubusercontent.com/assets/89725/15630729/000fa8ae-2582-11e6-8bb5-7f5a73d7ffc9.png">
Most of the lines there are just the annotations from syncing with Github. What I was trying to figure out, was how to get a listing of this the issue itself, without all the extra annotations there

**Comment by chrisidefix** [comment]
So what I understand is that you are using some way to sync github issues with task warrior and this in turn creates the annotations that you actually don't want to see? Unfortunately, I am not familiar with `bugwarrior`, but my logic here assumes that each `taskwarrior` output line is a new task.

I suppose the easiest solution would be to do some more string processing and just check if each line actually starts with a (valid) number and simply disregard lines that start with a date or lots of empty spaces, which should be very easy to detect.

All you need to do is add something like the code below to here:
https://github.com/matryer/bitbar-plugins/blob/aaeecd0ae8fc57fd2fba2bfd249c36e0b317cb78/Lifestyle/taskwarrior.4m.py#L61

```python
    for output_line in output_lines:
        content_id = content_line.split()[0]
        if content_id.isdigit():
            continue
        output_line = output_line.strip()
        if len(output_line) > 0:
            content_lines.append(output_line)
```

**Comment by kfdm** [comment]
Checking the first bit for .isdigit() looks reasonable enough and clean enough to do. If you're alright with that, I will write up a pull request as soon as I get a chance. Thanks again :)
