### ISSUE TITLE
re: CPU Temperature

### ISSUE THREAD

**Issue by Schuif67** [matryer/bitbar-plugins#434]
FAO: (@eripa)how do i get and install the SMC?

**Comment by eripa** [comment]
@Schuif67 info is in the meta-data for the plugin

 ```
'smc' can be downloaded from: http://www.eidac.de/smcfancontrol/smcfancontrol_2_4.zip
# One-liner:
# curl -LO http://www.eidac.de/smcfancontrol/smcfancontrol_2_4.zip && unzip -d temp_dir_smc smcfancontrol_2_4.zip && cp temp_dir_smc/smcFanControl.app/Contents/Resources/smc /usr/local/bin/smc ; rm -rf temp_dir_smc smcfancontrol_2_4.zip
```

**Comment by ipatch** [comment]
late to the party 🎉 as usual, but for those of us who have tapped [cask](https://github.com/caskroom/homebrew-cask) using homebrew getting this app is as simple as

```bash
brew cask install smcfancontrol
```

**Comment by ipatch** [comment]
late to the party 🎉 as usual, but for those of us who have tapped [cask](https://github.com/caskroom/homebrew-cask) using homebrew getting this app is as simple as

```bash
brew cask install smcfancontrol
```

and then

```bash
ln -sf /Applications/smcFanControl.app/Contents/Resources/smc /usr/local/bin/smc
```
