### ISSUE TITLE
re: Mac App Store

### ISSUE THREAD

**Issue by yrsengar** [matryer/bitbar-plugins#438]
FAO: (@iosdeveloper) Where and how to install mas?
When i installed this plugin it says "mas not installed" but there is no explanation on how and where to instal the "mas". I dont even know what mas actually is.
thank you

**Comment by iosdeveloper** [comment]
The description has a link to it: https://github.com/matryer/bitbar-plugins/blob/master/System/mas.1d.sh#L7
