### ISSUE TITLE
re: GitHub pull-requests

### ISSUE THREAD

**Issue by stefanosaittamrf** [matryer/bitbar-plugins#451]
FAO: (@jasminb)

For big output this dosn't work.

`Argument list too long`

I tried to fix myself redirecting the output into a file, and read the file using node but with no success because of some Permission Issues.

```bash
FILE_NAME="json"

curl -s -u $GITHUB_USER:$GITHUB_ACCESS_TOKEN $GITHUB_REPO_API/$GITHUB_REPO_OWNER/$GITHUB_REPO/pulls > $FILE_NAME
# JavaScript used to parse result JSON and extract titile/url/submitter of pull request
JS='var fs = require("fs"); fs.readFile("'$FILE_NAME'", "utf-8", function(err,data) {if(prJson=JSON.parse(data),prJson.length>0)for(console.log("♣︎ "+prJson.length+" PRs"),console.log("---"),i=0;i<prJson.length;i++)console.log("▸ #"+prJson[i].number+" "+prJson[i].title+" ("+prJson[i].user.login+") | href="+prJson[i].html_url);""; })'

# Fetch and parse open pull request from GitHub
node -pe "$JS"
```

This works fine in terminal, but not in bitbar. Let me know if you know how to solve the permission probelm :shipit:

**Comment by tresni** [comment]
This has been replaced with a new script [pull-requests.5m.js](Dev/GitHub/pull-requests.5m.js).  Can you verify if this is still an issue for you with the updated version?

**Comment by stefanosaittamrf** [comment]
@tresni I see that one, i refactored mine in ES6 starting form there. If you want open a PR there. I'm not about to publish this because have a dependecy with https://github.com/sindresorhus/bitbar but i guess you should take a look of that 👓
