### ISSUE TITLE
re: Virtualbox VM status - shutdown documentation

### ISSUE THREAD

**Issue by m-z-b** [matryer/bitbar-plugins#490]
FAO: (@aequitas)

It's worth noting in the description that this does a hard shutdown (poweroff) of the VM, possibly losing state, rather than a controlled ACPI shutdown.

**Comment by aequitas** [comment]
@m-z-b i added an ACPI shutdown option. Allowing the user to distinct between the performed action and allowing safe shutdown.

**Comment by tresni** [comment]
#491 is merged.
