### ISSUE TITLE
Columns, too?

### ISSUE THREAD

**Issue by irstacks** [matryer/bitbar-plugins#502]
My first idea when putting together #497 was for the emojis to span columns as well as rows, which might lead to a more available and compact layout. Perhaps maybe possible? 

(As it is now, you can render as many emojis per row as you'd want, but would have no way of differentiating a selection...)

**Comment by tresni** [comment]
This should be in [matryer/bitbar](https://github.com/matryer/bitbar) vs here..  We just keep the plugin repo clean ;-)
