### ISSUE TITLE
Do not automatically start work mode when a pomodoro is up

### ISSUE THREAD

**Issue by joelmccracken** [matryer/bitbar-plugins#503]
This may be a personal preference, but I do not like that work mode automatically restarts once break is over. If I had my preference, after a break, a pomodoro would end, 5 minutes would pass, and then an alert would state that the break is over.

**Comment by tresni** [comment]
FAO: @gorangajic

**Comment by gorangajic** [comment]
You can replace this line
https://github.com/matryer/bitbar-plugins/blob/529a1450aa17f29f2ab1961ca506ba85716fde67/Time/pomodoro.1s.sh#L98

with something like this

```changeStatus "0" "Break is over" "Blow"```

**Comment by joelmccracken** [comment]
ok! would this be a good PR/configuration option?

**Comment by tresni** [comment]
PRs are always welcome :)  Closing this ticket though as the main issue has a workaround and it's not really a bug, but preference.  The beauty of all of this is you can edit the script yourself :D

**Comment by joelmccracken** [comment]
Cool! If anyone else wants it I'm fine with making the change.
