### ISSUE TITLE
Move package_manager.py to its own repository

### ISSUE THREAD

**Issue by kdeldycke** [matryer/bitbar-plugins#525]
The [`package_manager.py`](https://getbitbar.com/plugins/Dev/package_manager.7h.py) script I created some weeks ago saw tremendous interests by the community. See: #466, #469, #479, #480, #482, #493, #498, #516, #520 and #523.

With time the script will grow bigger. Simply because we'll try to make its behaviour consistent and predictable in the face of highly variable environments. And also because we'll probably try to reduce the discrepancies between package managers.

We're not far from the symbolic size of 1000 lines, and I fear that any additional feature is going to bring it on the verge of unmaintainability.

Hence my proposal to move it to its own repository. This will allow us to let the script gets dedicated version tags, development and stable branches, documentation, unit-tests, version history, bug tracker, continuous integration and automatic code style checks.

I'm also thinking about putting all management code to a dedicated standalone Python package. This would add a dependency on the script itself, but nothing too complicated. We'll just need to `$ pip install package-manager`. This will greatly simplify the script itself.

What do you guys think of my proposal?

CC: @tresni, @keithamus

**Comment by keithamus** [comment]
> I'm also thinking about putting all management code to a dedicated standalone Python package. 

This sounds great. Make libraries not applications! It'd be great to repurpose this for other things.

**Comment by tresni** [comment]
I totally think it makes sense to move this to it's own repo for tracking changes, releases, etc.  Can still have the file included here too.

That is, unless you split it out into libraries...  If it's a `pip` installed library it should be fine, but just having a dependent module in the same folder won't (see standard response to any plugin that is more then a single file.)

**Comment by kdeldycke** [comment]
OK, so here is what I plan to do:

1. Isolate the script commit history and move it to a dedicated repository (already did that a couple of times).
2. Continue working on it over there, like we did in the past weeks, like nothing happened.
3. Push a copy of the standalone script here every time we release a tagged version.

That's all.

And while we keep working remotely on the standalone script, we'll experiment on a library on the side, in the same repository.

This might temporarily lead to duplicate code, but we'll have the whole project in one centralized place. There we'll have enough space to slowly think and lay out a plan for a painless transition, from the standalone script to a bare bitbar-script + a library.

**Comment by kdeldycke** [comment]
Here you go => https://github.com/kdeldycke/package-manager

**Comment by tresni** [comment]
I'm in :)

**Comment by kdeldycke** [comment]
Just gave you and @keithamus collaborator status to the repository, so I'll not be the bottleneck.

**Comment by kdeldycke** [comment]
We can now close this issue! :)

**Comment by santosh** [comment]
How to move a single file to it's won repo? Any ideas? I'm in same situation. The repo has multiple files, but I want one file to have it's own repo with history preserved. I looked up on SO but no answers were robust. Can you guys help me do this?
