### ISSUE TITLE
Plugin browser

### ISSUE THREAD

**Issue by matryer** [matryer/bitbar-plugins#53]
Guys,

I put together a very simple BitBar plugin browser: http://getbitbar.appspot.com (will be moved to getbitbar.com when it's ready). Real examples in the Tutorial section: http://getbitbar.appspot.com/plugins/Tutorial (and the source https://github.com/matryer/bitbar-plugins/blob/master/Tutorial/cycle_text_and_detail.sh)

By including metadata like the below in the plugin *source file*, authors can customise the browser:

```
# <bitbar.title>Cycle text and detail text</bitbar.title>
# <bitbar.version>1.0</bitbar.version>
# <bitbar.author>Mat Ryer</bitbar.author>
# <bitbar.author.github>matryer</bitbar.author.github>
# <bitbar.desc>Text above --- will be cycled through in the menu bar, whereas text underneath will be visible only when you open the menu.</bitbar.desc>
# <bitbar.image>http://www.images.com/path/to/image</bitbar.image>
```

It matches using regex, so tags may appear anywhere in the file (commented out however is suitable):

```
`<bitbar\.` + tag + `>(.*?)</bitbar\.` + tag + `>`
```

Would love some feedback, comments, bug reports, etc. over at https://github.com/matryer/getbitbar.com

**Comment by keithamus** [comment]
:+1: sounds great :smile:

**Comment by thameera** [comment]
A Search box would be handy.

Also, the link to the plugin browser's repo doesn't seem to work. (maybe private repo?)

**Comment by matryer** [comment]
Which link to plugins repo? It should link to THIS repo

**Comment by thameera** [comment]
I was referring to the link at the end of your comment: https://github.com/matryer/getbitbar.com

**Comment by maxoumime** [comment]
This is a really good idea, I like it !
And same here, I don't have access to your repo: https://github.com/matryer/getbitbar.com

**Comment by matryer** [comment]
Ahh yes - it’s public now

**Comment by matryer** [comment]
Plugins with metadata will now float to the top of the listings: https://getbitbar.com/plugins/System

**Comment by manojlds** [comment]
This is not accessible? - https://github.com/matryer/getbitbar.com
