### ISSUE TITLE
re: Travel time

### ISSUE THREAD

**Issue by BrokenFlows** [matryer/bitbar-plugins#544]
FAO: @katsuo11

Hi,

I'm sorry to bother you but I couldn't figure out how to set up Travel time for bit bar. I got two API keys through the links you gave but didn't know what to do beyond that.

I'd love it if you could direct me.

Thanks,
Cian

**Comment by tresni** [comment]
I believe his handle is now @ymilin but not sure that will get him as he hasn't done anything under that name in this project...

**Comment by ymilin** [comment]
Summoned :-)

I had to change handle, sorry about that.

I'm sorry if my instruction weren't clear enough, you only need one API key linked to a single Google developer project with both "Google Maps Distance Matrix API" and "Google Maps Geolocation API" APIs enabled.

## Instructions
1. Go to [https://console.developers.google.com/apis/](https://console.developers.google.com/apis/) and login with your Google account.
2. Create a project or select existing one.
3. Go to Dashboard and click on ENABLE API
![enable api](http://i.imgur.com/Bep4Yxv.png)
4. Under the Google Maps APIs section, you'll find links to "Google Maps Distance Matrix API" and "Google Maps Geolocation API".
![apis links](http://i.imgur.com/1URNtqv.png)
5. Open both links and click Enable for both APIs
![enable DM](http://i.imgur.com/Vnqv613.png)
![enable Geo](http://i.imgur.com/yOY3oxR.png)
6. Go to Credentials and select "API key" under "Create credentials" select box
![create Key](http://i.imgur.com/7s0SSKY.png)
7. save the generated API key to your clipboard (Ctrl+C)
![save key](http://i.imgur.com/fxx1apO.png)
8. edit the plugin file on line and paste your API key on line 27 inside the double quotes
9. Enter your destination on line 28 like you would on Google maps inside the double quotes.
![edit code](http://i.imgur.com/sEN1PDP.png)

I recommend updating the plugin every 15m minimum (i.e. use filename travel-time.15m.php)

And voilà!
![plugin screenshot](http://i.imgur.com/gyEWfXZ.png)

**Comment by ymilin** [comment]
@tresni 

I sent a PR for this plugin with my handle update :)

**Comment by tresni** [comment]
PRs merged and instructions provided.  Closing
