### ISSUE TITLE
re: Homebrew Cask Updater

### ISSUE THREAD

**Issue by km-tr** [matryer/bitbar-plugins#573]
FAO: (@srdgh)
This is no longer work correctly when homebrew cask is updated.

**Comment by Srdgh** [comment]
Thanks @km-tr . What exactly wasn't working? I've submitted a PR with a little fix because the word "From:" was appearing repeatedly in the menu. Let me know (once/if the PR is accepted) if this still isn't working.

**Comment by km-tr** [comment]
After updating to the latest the "homebrew cask", "brew cask info" to "Not installed" it will no longer be displayed

**Comment by Srdgh** [comment]
I'm sorry -- I don't fully understand. Could you give a bit more detail, please? I will do my best to solve this!

**Comment by km-tr** [comment]
This is latest ` brew cask info`
```sh
 ❯ brew cask info bitbar                                                                                                    [17:03:42]
bitbar: 1.9.2
https://github.com/matryer/bitbar/
/usr/local/Caskroom/bitbar/1.6.0 (does not exist)
/usr/local/Caskroom/bitbar/1.7.0 (does not exist)
/usr/local/Caskroom/bitbar/1.9.0 (does not exist)
/usr/local/Caskroom/bitbar/1.9.1 (does not exist)
/usr/local/Caskroom/bitbar/1.9.2 (68B)
From: https://github.com/caskroom/homebrew-cask/blob/master/Casks/bitbar.rb
==> Name
BitBar
==> Artifacts
BitBar.app (app)
```

It is not displayed "Not installed".

**Comment by Srdgh** [comment]
OK. But it looks like that's because you do have the current version of bitbar installed (as shown by the line `/usr/local/Caskroom/bitbar/1.9.2 (68B)`)? When I `brew cask info` for an app I don't have installed, I still get "Not Installed".

**Comment by Srdgh** [comment]
(I must be missing something?)

**Comment by km-tr** [comment]
==> My Homebrew-Cask Version:
0.60.0 (git revision 904b8e; last commit 6 hours ago)

**Comment by Srdgh** [comment]
I'm confused. Based on the docs at https://github.com/caskroom/homebrew-cask/blob/master/USAGE.md homebrew automatically keeps homebrew cask updated. My Homebrew is Homebrew 1.0.6 (git revision c7cc; last commit 2016-10-07). (i.e. up-to-date today), and I get "Not Installed" when I `brew cask info` a cask which is not installed.

In the same doc, it gives an example of `brew cask info` on caffeine:
`$ brew cask info caffeine
caffeine: 1.1.1
http://lightheadsw.com/caffeine/
Not installed
From: https://github.com/caskroom/homebrew-cask/blob/master/Casks/caffeine.rb
==> Name
Caffeine
==> Artifacts
Caffeine.app (app)`

That means this plugin is as up-to-date as the docs. The example you pasted above seems to be of an installed cask. Could you paste an example of `brew cask info` on a cask which is not installed? I think that might help me understand what I'm missing.

**Comment by Srdgh** [comment]
I notice that the doc I quoted above hasn't been updated for 10 days. It would be great if someone who knows the new format could update USAGE.md. If you happen to know what has changed, or where I can find documentation describing the new format, I'd appreciate it.

**Comment by km-tr** [comment]
I also notice now that

- App that has not yet been installed even once (it display `Not installed`)
```sh
# example
 ❯ brew cask info caffeine                                                                                                  [19:54:14]
caffeine: 1.1.1
http://lightheadsw.com/caffeine/
Not installed
From: https://github.com/caskroom/homebrew-cask/blob/master/Casks/caffeine.rb
==> Name
Caffeine
==> Artifacts
Caffeine.app (app)
```

- Already installed apps
```
# example
❯ brew cask info bitbar                                                                                                    [19:54:00]
bitbar: 1.9.2
https://github.com/matryer/bitbar/
/usr/local/Caskroom/bitbar/1.6.0 (does not exist)
/usr/local/Caskroom/bitbar/1.7.0 (does not exist)
/usr/local/Caskroom/bitbar/1.9.0 (does not exist)
/usr/local/Caskroom/bitbar/1.9.1 (does not exist)
/usr/local/Caskroom/bitbar/1.9.2 (68B)
From: https://github.com/caskroom/homebrew-cask/blob/master/Casks/bitbar.rb
==> Name
BitBar
==> Artifacts
BitBar.app (app)
```

**Comment by Srdgh** [comment]
Thank you. Great -- so is everything working properly?

**Comment by km-tr** [comment]
Yes!

**Comment by Srdgh** [comment]
Perfect! :)
