### ISSUE TITLE
Pi-Hole not found strangeness.

### ISSUE THREAD

**Issue by escapologyBB** [matryer/bitbar-plugins#574]
Firstly, this is a great plug-in and worked really well until this morning when it just suddenly stopped working and instead of seeing a globe in the menu bar of my laptop and my iMac I now see a red cross.  I had the configuration file on a shared folder in Dropbox so I thought that might be the problem and separated the configuration files so each machine had its own file, but that didn't help and I'm still stuck with the red cross in my menu bar.

The output you see below is what I get when I use the command `Run in Terminal`

I have changed nothing in the configuration files since the day I downloaded it other than to change the IP address from `192.168.0.101` to `192.168.0.55` which is the address of my Pi-Hole.  The plug-in just suddenly stopped working.  Any idea how I might be able to fix this really useful plug-in?

Thanks in advance!

```
➜  ~ /Users/user/bin/bitbar/pi-hole.1m.py
❌
---
Pi-Hole not found | color=red
---
➜  ~ 
```

**Comment by escapologyBB** [comment]
I know nothing about Python that if I change the line:

`result = urllib2.urlopen(url, timeout = 5).read()`

So that it says:

`result = urllib2.urlopen(url, timeout = 10).read()`

Everything is now working perfectly!  Does this seem like a reasonable change to make?  Like I say I know nothing about the Python programming language so this may have consequences that I know nothing about, what do you guys think?

**Comment by tresni** [comment]
That should be an acceptable change.  Just means that python will wait 10 seconds before timing out the connection (and/or read) to the device.

**Comment by escapologyBB** [comment]
Excellent, I will close this issue then as it is still working perfectly.

Cheers!
