### ISSUE TITLE
Fails when bitbar plugins folder is in a folder containing a space in it's name

### ISSUE THREAD

**Issue by Gruntfuggly** [matryer/bitbar-plugins#583]
I placed the bitbar-plugins folder in **Library/Application Support**. I noticed that some plugins didn't work and when running with terminal output enabled, the output was:

```
Last login: Wed Oct 12 15:48:36 on ttys005
/Users/ns/Library/Application     
• [~] ns $ /Users/ns/Library/Application     
-bash: /Users/ns/Library/Application: No such file or directory
• [~] ns $ 
```

It looks like the path needs to be quoted.

**Comment by tresni** [comment]
This is a known issue.  It depends on how the plugins are written.

```
# The following will fail if the path has a space in it:
Test | bash=$0 param1=hello param2=world

# Correct solution is to encase in quotes:
Test | bash="$0" param1=hello param2=world
```

Neither of these will work if you do "Run in Terminal" though as it does not wrap the arguments in quotes or do any string escaping before outputting to Terminal.
