### ISSUE TITLE
re: Weather

### ISSUE THREAD

**Issue by amdemas** [matryer/bitbar-plugins#588]
FAO: (@seripap) 

It seems that forecast.io is no more and has been replaced with darkskys. Everything seems to still be working except the map. Is there any plans to update this plugin? Thanks!

![screen shot 2016-10-20 at 11 58 29 pm](https://cloud.githubusercontent.com/assets/1113392/19586217/2e426958-9721-11e6-993c-6257131c212e.png)

**Comment by seripap** [comment]
Unfortunately this technically was an "undocumented" feature of forecast.io using what was on their website. When they switched over to the "newer" DarkSky, the static map images were removed and can no longer be referenced. 

I've removed the image and updated the API calls to the newer endpoints, hopefully will be merged soon.

**Comment by amdemas** [comment]
Darn, that was a nice feature. Thanks for the update!
