### ISSUE TITLE
re: Live Cricket Scores

### ISSUE THREAD

**Issue by asiriwork** [matryer/bitbar-plugins#603]
Doesn't work with osx sierra FAO: (@anupsabraham)

**Comment by anupsabraham** [comment]
I am using sierra right now and it is working. Can you share more details about what error you're getting? Try running it in terminal.

**Comment by asiriwork** [comment]
That SA 0/0 is different app. This is what is looks like. And thank you for the quick response. 




Regards,
Asiri

**Comment by asiriwork** [comment]
Output of running it on terminal.

$ /Users/asiri/Apps/Utilities/Menu\ Bar/BitbarPluginFolder/live_cricket.2m.py
🏏
---
No matches live
---
Favorite Teams | color=green
--Click on any to remove from favorites
-----
--You don't have any favorite teams set
Other Teams | color=red
--Click on any to add to favorites
-----
--Northern Cpe | terminal=false bash="/Users/asiri/Apps/Utilities/Menu Bar/BitbarPluginFolder/live_cricket.2m.py" param1="-i" param2="Northern Cpe" refresh=true
--W Province | terminal=false bash="/Users/asiri/Apps/Utilities/Menu Bar/BitbarPluginFolder/live_cricket.2m.py" param1="-i" param2="W Province" refresh=true
--LIONS | terminal=false bash="/Users/asiri/Apps/Utilities/Menu Bar/BitbarPluginFolder/live_cricket.2m.py" param1="-i" param2="LIONS" refresh=true
--Titans | terminal=false bash="/Users/asiri/Apps/Utilities/Menu Bar/BitbarPluginFolder/live_cricket.2m.py" param1="-i" param2="Titans" refresh=true
--Queensland | terminal=false bash="/Users/asiri/Apps/Utilities/Menu Bar/BitbarPluginFolder/live_cricket.2m.py" param1="-i" param2="Queensland" refresh=true
--Victoria | terminal=false bash="/Users/asiri/Apps/Utilities/Menu Bar/BitbarPluginFolder/live_cricket.2m.py" param1="-i" param2="Victoria" refresh=true
--Victorians | terminal=false bash="/Users/asiri/Apps/Utilities/Menu Bar/BitbarPluginFolder/live_cricket.2m.py" param1="-i" param2="Victorians" refresh=true
--Raj Kings | terminal=false bash="/Users/asiri/Apps/Utilities/Menu Bar/BitbarPluginFolder/live_cricket.2m.py" param1="-i" param2="Raj Kings" refresh=true
--Dolphins | terminal=false bash="/Users/asiri/Apps/Utilities/Menu Bar/BitbarPluginFolder/live_cricket.2m.py" param1="-i" param2="Dolphins" refresh=true
--Cape Cobras | terminal=false bash="/Users/asiri/Apps/Utilities/Menu Bar/BitbarPluginFolder/live_cricket.2m.py" param1="-i" param2="Cape Cobras" refresh=true
--Riders | terminal=false bash="/Users/asiri/Apps/Utilities/Menu Bar/BitbarPluginFolder/live_cricket.2m.py" param1="-i" param2="Riders" refresh=true
--Titans | terminal=false bash="/Users/asiri/Apps/Utilities/Menu Bar/BitbarPluginFolder/live_cricket.2m.py" param1="-i" param2="Titans" refresh=true
--Warriors | terminal=false bash="/Users/asiri/Apps/Utilities/Menu Bar/BitbarPluginFolder/live_cricket.2m.py" param1="-i" param2="Warriors" refresh=true
--Knights | terminal=false bash="/Users/asiri/Apps/Utilities/Menu Bar/BitbarPluginFolder/live_cricket.2m.py" param1="-i" param2="Knights" refresh=true
--KZN-Inland | terminal=false bash="/Users/asiri/Apps/Utilities/Menu Bar/BitbarPluginFolder/live_cricket.2m.py" param1="-i" param2="KZN-Inland" refresh=true
--S West D | terminal=false bash="/Users/asiri/Apps/Utilities/Menu Bar/BitbarPluginFolder/live_cricket.2m.py" param1="-i" param2="S West D" refresh=true
--China | terminal=false bash="/Users/asiri/Apps/Utilities/Menu Bar/BitbarPluginFolder/live_cricket.2m.py" param1="-i" param2="China" refresh=true
--South Korea | terminal=false bash="/Users/asiri/Apps/Utilities/Menu Bar/BitbarPluginFolder/live_cricket.2m.py" param1="-i" param2="South Korea" refresh=true
--South Africa | terminal=false bash="/Users/asiri/Apps/Utilities/Menu Bar/BitbarPluginFolder/live_cricket.2m.py" param1="-i" param2="South Africa" refresh=true
--Australia | terminal=false bash="/Users/asiri/Apps/Utilities/Menu Bar/BitbarPluginFolder/live_cricket.2m.py" param1="-i" param2="Australia" refresh=true
--Japan | terminal=false bash="/Users/asiri/Apps/Utilities/Menu Bar/BitbarPluginFolder/live_cricket.2m.py" param1="-i" param2="Japan" refresh=true
--HK Dragons | terminal=false bash="/Users/asiri/Apps/Utilities/Menu Bar/BitbarPluginFolder/live_cricket.2m.py" param1="-i" param2="HK Dragons" refresh=true
--Denmark | terminal=false bash="/Users/asiri/Apps/Utilities/Menu Bar/BitbarPluginFolder/live_cricket.2m.py" param1="-i" param2="Denmark" refresh=true
--Oman | terminal=false bash="/Users/asiri/Apps/Utilities/Menu Bar/BitbarPluginFolder/live_cricket.2m.py" param1="-i" param2="Oman" refresh=true
--U.S.A. | terminal=false bash="/Users/asiri/Apps/Utilities/Menu Bar/BitbarPluginFolder/live_cricket.2m.py" param1="-i" param2="U.S.A." refresh=true
--Jersey | terminal=false bash="/Users/asiri/Apps/Utilities/Menu Bar/BitbarPluginFolder/live_cricket.2m.py" param1="-i" param2="Jersey" refresh=true
--Bermuda | terminal=false bash="/Users/asiri/Apps/Utilities/Menu Bar/BitbarPluginFolder/live_cricket.2m.py" param1="-i" param2="Bermuda" refresh=true
--Italy | terminal=false bash="/Users/asiri/Apps/Utilities/Menu Bar/BitbarPluginFolder/live_cricket.2m.py" param1="-i" param2="Italy" refresh=true
--Tasmania | terminal=false bash="/Users/asiri/Apps/Utilities/Menu Bar/BitbarPluginFolder/live_cricket.2m.py" param1="-i" param2="Tasmania" refresh=true
--South Aust | terminal=false bash="/Users/asiri/Apps/Utilities/Menu Bar/BitbarPluginFolder/live_cricket.2m.py" param1="-i" param2="South Aust" refresh=true
--West Aust | terminal=false bash="/Users/asiri/Apps/Utilities/Menu Bar/BitbarPluginFolder/live_cricket.2m.py" param1="-i" param2="West Aust" refresh=true
--NSW | terminal=false bash="/Users/asiri/Apps/Utilities/Menu Bar/BitbarPluginFolder/live_cricket.2m.py" param1="-i" param2="NSW" refresh=true
--Hong Kong | terminal=false bash="/Users/asiri/Apps/Utilities/Menu Bar/BitbarPluginFolder/live_cricket.2m.py" param1="-i" param2="Hong Kong" refresh=true
--P.N.G. | terminal=false bash="/Users/asiri/Apps/Utilities/Menu Bar/BitbarPluginFolder/live_cricket.2m.py" param1="-i" param2="P.N.G." refresh=true
--TRACK ALL TEAMS | terminal=false bash="/Users/asiri/Apps/Utilities/Menu Bar/BitbarPluginFolder/live_cricket.2m.py" param1="-i" param2="*" refresh=true
ALA:~ Asiri$

**Comment by anupsabraham** [comment]
Output seems alright. Can you attach a screenshot here.

**Comment by anupsabraham** [comment]
Ok. I see you tried attaching a screenshot in your reply. But I'm not able to see that in the comment.

**Comment by tresni** [comment]
Closing due to lack of response
