### ISSUE TITLE
re: Pi-hole status

### ISSUE THREAD

**Issue by Jacob-Gingleheimer** [matryer/bitbar-plugins#605]
FAO: (@siimots) Not an issue, but a minor tweak that I did on my end that I thought you might enjoy
   

    result = urllib2.urlopen(url, timeout = 10).read()
    json = json.loads(result)
    print "🌍"
    print "---"
    print "Ads blocked:"
    print json['ads_blocked_today'] + "| color=blue"
    print "Percentage of total traffic:"
    print json['ads_percentage_today'] + "| color=orange"
    print "DNS queries:"
    print json['dns_queries_today'] + "| color=green"
    print "Domain list size:"
    print json['domains_being_blocked'] + "| color=red"
    print "Check it out | href=" + pihole
    print "---"

**Comment by tresni** [comment]
Closing.  A PR can be submitted if this change is to be incorporated.
