### ISSUE TITLE
re: SpursBar

### ISSUE THREAD

**Issue by jdgoal14** [matryer/bitbar-plugins#607]
FAO: (@coreyk) is there a way that this can be configured for other premier league teams? How about another team from another league.

**Comment by coreyk** [comment]
It uses the BBC Sport website for data, so you could modify it to use any of the PL team sites they have by changing line 39:
https://github.com/matryer/bitbar-plugins/blob/master/Sports/SpursBar.6h.rb#L39
to the other team's URL, like:
`@team = Nokogiri::HTML(open("http://www.bbc.com/sport/football/teams/tottenham-hotspur"))`
to
@team = Nokogiri::HTML(open("http://www.bbc.com/sport/football/teams/watford"))

Possibly even other leagues.
Give it a try.
