### ISSUE TITLE
re: Weather Underground

### ISSUE THREAD

**Issue by eboye** [matryer/bitbar-plugins#609]
FAO: (@asnodgrass)

I keep getting missing key error, but it actually is set:

![scr- 2016-11-21 at 20 21 17](https://cloud.githubusercontent.com/assets/624357/20497111/360cbede-b028-11e6-814b-3ec74e3ea487.png)

When I run the plugin in terminal, I get the results:

![screenshot 2016-11-21 at 20](https://cloud.githubusercontent.com/assets/624357/20497147/58e4bce0-b028-11e6-9e51-16d1e3bd345e.png)

**Comment by asnodgrass** [comment]
@eboye Can you confirm that Bitbar is using the copy of the plugin with your key in it, and not the vanilla version straight from the repository? I'm not able to replicate this issue locally, as I get the same output from the plugin with both manual execution and use via Bitbar (as expected).

**Comment by eboye** [comment]
@asnodgrass yes. It didn't even work in the first place with Vanilla one. I checked it before submitting the bug. It's not always doing that, but on a random occasion. Currently it is working as expected.

![scr- 2016-11-23 at 03 19 49](https://cloud.githubusercontent.com/assets/624357/20549361/c4a8693c-b12b-11e6-80eb-5d0d8340df13.png)

But today it broke multiple times. I'm not quite sure what could be the problem. I have little snitch installed, but even when I disable it, it still get's that problem (I thought maybe it was blocking it).

Anyway, not a big issue, just wanted to report. I'm using the plugin for quite some time and didn't have any issues until recent.

Thanks

**Comment by asnodgrass** [comment]
@eboye What's odd about this is that I explicitly rescue `Wunderground::MissingAPIKey` and provide a (slightly) different error message; instead, `Wunderground::APIError` is being reached, and the output you get inside the dropdown is the literal text from the WU API server.  It may be that something has changed in the API that the `wunderground` gem isn't accounting for properly, or the API service is providing unexpected and erroneous responses.

I suspect that given the inconsistency of your error that WU may have (or had?) a broken API server in their load balancer pool. If it recurs, I'd check their API pages for a contact or support form and see what they have to say about the issue.

**Comment by eboye** [comment]
@asnodgrass Sounds reasonable 👍  Will check with them. I never used their API ... I often use Yahoo as it's very well documented and I'm really bad with ruby :)
