### ISSUE TITLE
re: Meta Package Manager - Updating All python, npn, and ruby does not work

### ISSUE THREAD

**Issue by rkrug** [matryer/bitbar-plugins#621]
FAO: (@kdeldycke)

Am I doing something wrong or do I have to do something special to update all packages in python, npon and ruby? Clicking "update all" does not install anything. actually, it seems I can't install anything? Except homebrew.

**Comment by kdeldycke** [comment]
I did not really implemented the `pip`, `npm` and `gem` managers. @tresni did. I merely repackaged his core implementation but while doing so I might have overlooked a detail or two.

To help me debug, can you [migrate to the new v2.x series](https://github.com/matryer/bitbar-plugins/pull/625#issuecomment-267182585) plugin? Does that new v2.1.0 version fix anything?

If not, running the underlying `mpm` CLI in a terminal in debug mode might provides some clues:
```shell
$ mpm --manager pip2 --verbosity DEBUG upgrade
```

**Comment by rkrug** [comment]
Some questions. 

Upgrade: to v2.x series: I just installed again using the BitBar plugins and also looked at GitHub (https://github.com/matryer/bitbar-plugins/tree/master/Dev/MetaPackageManager) but it still seems to be the 1.x series there?

mpm: I tried "pip install mpm" and it works (the installation), but I can't access it from the command line. Any suggestions?

**Comment by rkrug** [comment]
mpm: installed it using 

```
pip install meta-package-manager
```

and it worked.
Just trying to upgrade the packages from there - will poet if it doesn't work.

```
warning: Skip unavailable cask manager.
warning: Skip unavailable brew manager.
```

Home-brew and Home-brew Cask, I get ``` 1.1.4-2-g9cd5a21b47 >= 1.0.0``` and it doesn't work with home-brew?

**Comment by rkrug** [comment]
There are problems with the upgrade of pip2 - pip3 is fine., problems with access rights. I will ask these at https://github.com/kdeldycke/meta-package-manager - is that the correct place?

**Comment by kdeldycke** [comment]
The v2.x plugin hasn't been merged yet upstream. See #625.

[`mpm` Python module](https://pypi.python.org/pypi/mpm) is not the same as [`meta-package-manager`](https://pypi.python.org/pypi/meta-package-manager). But you figured that out yourself! :)

The problem with `1.1.4-2-g9cd5a21b47 >= 1.0.0` version comparison has been identified in https://github.com/kdeldycke/meta-package-manager/issues/15 . I'll fix that soon.

I'm not surprised by rights and ownership issues. Maybe some Python package where installed with `sudo`.

Anyway you're right, to not pollute this repository with unrelated issues, let's continue the discussion on packages and managers at https://github.com/kdeldycke/meta-package-manager .

**Comment by rkrug** [comment]
Just one final here: What is the "official" way to update the bitter plugin, as the bitter plugin still seems to have the 1.x series?

**Comment by kdeldycke** [comment]
You're just an early adopter! :) Wait for a couple of days and @tresni will surely merge #625.

**Comment by tresni** [comment]
Closing this to be continued in kdeldycke/meta-package-manager as required.
