### ISSUE TITLE
Githubzen returns 401 Unauthorized

### ISSUE THREAD

**Issue by aj07mm** [matryer/bitbar-plugins#631]
FAO: (@andjosh)

Githubzen returns a 401 Unauthorized.

<img width="781" alt="screen shot 2016-12-19 at 01 17 17" src="https://cloud.githubusercontent.com/assets/3050129/21300186/f472ab7a-c588-11e6-977c-62d7a44e520f.png">

**Comment by tresni** [comment]
@aj07mm did you [edit the githubzen.1m.py file and put in your Github Token](https://github.com/matryer/bitbar-plugins/blob/33ee007d4df75bb2305b1d3888aefe4dc537913c/Lifestyle/githubzen.1m.py#L15)?
