### ISSUE TITLE
re: PIA VPN Status

### ISSUE THREAD

**Issue by YoDanzzy** [matryer/bitbar-plugins#645]
FAO: (@parvez) can't get it working with version BitBar 1.9.2
All I am given is the yellow caution sign and the red circle when indeed I am connected with PIA and the websites shows the same.

hope theres a fix

**Comment by parvez** [comment]
Thanks for alerting. I had fixed this on my mac, but forgot to update here. I have submitted a PR for the fix. Thanks! P

#https://github.com/matryer/bitbar-plugins/pull/646
