### ISSUE TITLE
a fix but just one problem

### ISSUE THREAD

**Issue by YoDanzzy** [matryer/bitbar-plugins#647]
sorry to bother again, its just a great thing you have here and I really want it to work.

just did what you sent and this is what I'm getting now 
<img width="752" alt="screen shot 2017-01-09 at 2 50 54 am" src="https://cloud.githubusercontent.com/assets/25000573/21760018/d64383f6-d616-11e6-81d9-72ff05d2a11b.png">

<img width="45" alt="screen shot 2017-01-09 at 2 50 47 am" src="https://cloud.githubusercontent.com/assets/25000573/21760021/da432434-d616-11e6-9cff-13f885217cb5.png">

this time it recognizes that I'm connected but the yellow thing still pops up
Please help me man, it would be awesome!

**Comment by tresni** [comment]
`brew install gnu-sed`  or install GNU sed some other way :)
