### ISSUE TITLE
re: Simple ToDo Tracker for Markdown

### ISSUE THREAD

**Issue by jeffchasin** [matryer/bitbar-plugins#652]
FAO: (@artifactsauce) Sorry for the dumb question - how is the ToDo list in the .md file supposed to be formatted? I tried just about every list type & heading marker w no luck.

```
* Unfinished item
- Unfinished item
[ ] Unfinished item
x Unfinished item
# Unfinished item
```

Any suggestions appreciated. Thanks very much

**Comment by tresni** [comment]
Based on the regex in the file it looks like this:

```md
* [x] finished
* [ ] unfinished
- [ ] unfinished
- [x] finished
1. [ ] test 3
2. [x] finished
```

If using number format, it only appears to allow 10 items (0-9 [it uses`\d` in regex vs `\d+` which would match multiple digits])

Also, be aware that it's really strict on formatting.  Must have spaces before, after, and between the square brackets `[]`.  Must use an `x` to indicate complete (anything else means incomplete.)  Number format must be single digit followed by a period.
