### ISSUE TITLE
Security?

### ISSUE THREAD

**Issue by JaKXz** [matryer/bitbar-plugins#66]
This might be a dumb question, but, is there any way we can ensure that these scripts we're simply `chmod +x`ing on our machines are not malicious? I'm not necessarily questioning the integrity of the community, but I am curious if this has been thought about...

**Comment by matryer** [comment]
This is why BitBar has to be directly downloaded, rather than through the App Store. It's a real consideration. We do a review (which includes security) of all plugins before accepting them. Do you have any other suggestions that could help?

**Comment by manojlds** [comment]
Considering the target (developers), I would suggest you read through the plugin you want to use. Not even going to the level of malicious scripts, it might just be prudent to know what you are running.

**Comment by maxoumime** [comment]
I was thinking about a way to inject some of our informations by using environment variables, instead of hard writing those informations on the script itself. Maybe using a Preferences or something ?

**Comment by manojlds** [comment]
@maxoumime there is ongoing discussion here - https://github.com/matryer/bitbar/issues/88

**Comment by JaKXz** [comment]
> It's a real consideration. We do a review (which includes security) of all plugins before accepting them.

@matryer thanks for the response - I don't have any concrete suggestions right now, but I just wanted to get a discussion going. Feel free to close this issue; leaving it open might help others find it and contribute, though.

> Considering the target (developers), I would suggest you read through the plugin you want to use. Not even going to the level of malicious scripts, it might just be prudent to know what you are running.

@manojlds I agree! The reason I ask is more because I'm not entirely familiar with all the languages used to write these plugins, so my intuition would only take me so far. Of course I'll be deep diving on things that I'm curious about or concerned about, but again, just wanted to raise a conversation point.

**Comment by manojlds** [comment]
@JaKXz - yeah definitely. Boils down to community + own checks.
