### ISSUE TITLE
re: Screenshotter

### ISSUE THREAD

**Issue by insawagner** [matryer/bitbar-plugins#661]
FAO: (@moshed)

Hello. What does "requires alerter" mean? Do I need to download something special? It currently doesn't "do" anything when I take a screenshot. Shouldn't it ask for some path? (I read that there's imgur as an option a s well.) Thank you!

**Comment by moshed** [comment]
yeah i meant to add links to the dependencies https://github.com/vjeantet/alerter/releases so download that. it proabbaly wont work for you in its current satte as i realized that there a couple of things that are hardcoded to my setup so i need to fix them up a little

**Comment by moshed** [comment]
#665 should fix issues and allow you to choose file paths and stuff. let me know how it goes
