### ISSUE TITLE
re: Transmission Remote

### ISSUE THREAD

**Issue by jdgoal14** [matryer/bitbar-plugins#667]
FAO: (@christophruss)

Hi 

Is there a step by step guide or youtube video on how to set up the transmission remote for bitbar.

Thanks

Jason

**Comment by tresni** [comment]
These steps assume you have [homebrew](http://brew.sh) installed.

1. `brew install transmission`
1. `pip install keyring` (you may need to do `sudo pip install keyring` depending on your system setup)
1. `python $PATH_TO_YOUR_BITBAR_PLUGINS_FOLDER\transmission.4m.py init`

You will be prompted with a series of questions, answer them.  That should really be it.
