### ISSUE TITLE
re: Gmail Checker

### ISSUE THREAD

**Issue by joeynotjoe** [matryer/bitbar-plugins#668]
FAO: (@nadavc)
Is there a way to configure this to work with an account that has 2FA enabled?

*edit: my apologies if this is the same question being asked here: #410

**Comment by nadavc** [comment]
I believe you can generate an [app-specific password](https://support.google.com/accounts/answer/185833?hl=en) via Google Accounts to bypass 2FA. It makes access less secure, but you can remove access from that password if you ever feel like it's been compromised.
