### ISSUE TITLE
re: Google Finance Stock Ticker

### ISSUE THREAD

**Issue by tsnosaj** [matryer/bitbar-plugins#679]
FAO: (@jamiesonio) How do I add UK stocks?  I have tried adding the suffix .L e.g. WPG.L to differentiate Worldpay (in the UK) from the Washington Prime Group but the script does not seem to like it.  Cheers JKST

**Comment by JanGross** [comment]
Is this what you're looking for?  
```py 
stocks={"WPG","LON:WPG"}  
```  

![bildschirmfoto 2017-02-06 um 09 36 38](https://cloud.githubusercontent.com/assets/13641301/22639755/d399267a-ec4f-11e6-88fe-b10de6fcc884.png)
