### ISSUE TITLE
Syntax error, extra double dot on last line

### ISSUE THREAD

**Issue by nei** [matryer/bitbar-plugins#681]
I just downloaded it and I've got this syntax error.
```
print item + ' | font=Monaco size=11':
```
It came with this double dot on the last line removed it and went fine.

Python version 2.7.13

**Comment by tresni** [comment]
Hi @nei - what script was this?

**Comment by nei** [comment]
it was the currency-rate but it was my bad.. when I downloaded from raw version it came with an additional code at the end. I doubled checked and seems good.
