### ISSUE TITLE
re: Todoist Today

### ISSUE THREAD

**Issue by yigitkonur** [matryer/bitbar-plugins#700]
FAO: (@chiisaihayashi)

Hi there - Todoist integration is not working even I write API key into .py script. Do you have any solution?

**Comment by tresni** [comment]
May want to review #358 to make sure you aren't running into the same issues.

**Comment by chiisaihayashi** [comment]
Hi,
Could you fix this issue? As long as my environment, that works. If you still have trouble, please let me know.
