### ISSUE TITLE
re: PagerDuty Incidents

### ISSUE THREAD

**Issue by parabuzzle** [matryer/bitbar-plugins#708]
FAO: (@pedrofuentes)
I've tested that my token works against the api but I'm getting this error:

```
(node:11322) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'forEach' of undefined
(node:11322) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by parabuzzle** [comment]
It appears that this plugin doesn't support the PagerDuty V2 api. In order to fix this, I generated a V1 key and it seems to work now. That should be documented somewhere.

**Comment by matryer** [comment]
We’d love a PR since you know the issue?

**Comment by pedrofuentes** [comment]
Thank @parabuzzle,

I have documentation on [my repo](https://github.com/pedrofuentes/bitbar-plugins/tree/master/pagerDutyIncidents) but I did not clarify there that a v1 API key was needed, I just fixed it.

I also plan at some point to [migrate to v2](https://github.com/pedrofuentes/bitbar-plugins/issues/1), contributions are welcome.

**Comment by parabuzzle** [comment]
good enough for me :)

**Comment by pedrofuentes** [comment]
@parabuzzle I just updated the code to work with PagerDuty v2 API
