### ISSUE TITLE
re: Timezone

### ISSUE THREAD

**Issue by sergioka** [matryer/bitbar-plugins#724]
FAO: (@xremix)
How do I set the Timezone for Brazil / São Paulo? I've tried several formats that I knew... Is there a list of formats that I can follow to change to other time zones?
Tks

**Comment by xremix** [comment]
@sergioka you can check the available timezones at `/usr/share/zoneinfo` and follow the file path available there.
So you could for example use `America/Sao_Paulo` or  `Brazil/East` if I'm correct.

Does that work for you?
Btw. there should be some comment in the source code about that, but I can clarify this a bit.

**Comment by xremix** [comment]
@matryer can be closed I guess
docs are provided in the code, but I can also make it more descriptive at some point

**Comment by sergioka** [comment]
@xremix that's great. It was pretty straight forward, my difficulty was to find out the right syntax for the country/city (I've tried several things). Now it's working. Thanks!
