### ISSUE TITLE
re: Instagram Stats

### ISSUE THREAD

**Issue by MrJarnould** [matryer/bitbar-plugins#725]
FAO: (@JanGross)

Hello Jan,

Can you please update this plugin?  There are many bugs.

I am constantly getting the error: 
```
print(formatted_bio + "
"UnicodeEncoreError: 'ascii' codec can't encode characters in position 176-179: ordinal not in range(128)"
```
Thanks

**Comment by JanGross** [comment]
Sure, I'll look into this issue. What username did you use that was causing this bug?
