### ISSUE TITLE
re: Moon Phase

### ISSUE THREAD

**Issue by pop4tune** [matryer/bitbar-plugins#733]
FAO: (@hpcodecraft) doesn't work for me - shows "Couldn't posix_spawn: error 2". Terminal tells "-bash: /Users/myuser/Library/Mobile Documents/com~apple~CloudDocs/bitbar/moon-phase.1h.js: /usr/local/bin/node: bad interpreter: No such file or directory"

**Comment by hpcodecraft** [comment]
@pop4tune You need to have node installed in order to run it. If you have homebrew, you can do it with `brew install node`
