### ISSUE TITLE
Any way to change color of words from python?

### ISSUE THREAD

**Issue by dzg** [matryer/bitbar-plugins#735]
Something like
`print 'LA \033[92m ', t1, 'NY \033[94m ', t2`
doesn't change colors .. any way to do it?

(I want this for the title, not the dropdown, see image)

![image](https://cloud.githubusercontent.com/assets/466557/24616848/8fbd62c6-1892-11e7-8c9a-468928c4f7e8.png)

**Comment by tresni** [comment]
See https://github.com/matryer/bitbar-plugins/blob/master/Tutorial/ansi.sh

We don't support the 256-color or high intensity colors.  Just the standard `\033[30m` - `\033[37m`, with `\033[1m` to toggle "bold" (ie brighter).  Use `40` - `47` for background colors.

So try:
* `\033[92m` -> `\033[1;32m`
* `\033[94m` -> `\033[1;34m`

**Comment by dzg** [comment]
Aha! That works, thanks!

Another tiny issue ... maybe not worth its own thread ...

I have 2 python scripts, which just show some text as title, but they do not line up vertically.
One is timezones clock, the second is EURUSD exchange rate.

![image](https://cloud.githubusercontent.com/assets/466557/24628709/c4a190e6-18b7-11e7-8633-f52d785a3af4.png)

The `1.0668` is a few pixels higher. Any idea why?

**Comment by tresni** [comment]
You are probably seeing matryer/bitbar#376.
