### ISSUE TITLE
Re: Habitica | Invalid Array Length

### ISSUE THREAD

**Issue by awitherow** [matryer/bitbar-plugins#742]
<img width="658" alt="screen shot 2017-04-08 at 16 37 55" src="https://cloud.githubusercontent.com/assets/1827147/24829847/e60eb98c-1c79-11e7-8c0a-c5c9a3cbacdb.png">

First of all, awesome thing! Really excited to use this 👍 

I added my api user and token and I am getting this error.

The code erroring is in this block is here:

```javascript
const progressBar = function(n, total, charLength) {
  n = Math.max(n, 0); // Health can be negative

  charLength = charLength || 10;

  const progress = (n / total) * charLength;
  const ish = progress % 1;

  const filled = Array(Math.floor(progress) + 1).join(FILLED);
  const middle = ish ? FILLEDISH[Math.ceil(FILLEDISH.length * ish) - 1] : false;
  const unfilled = Array(charLength - Math.floor(progress) + (middle ? 0 : 1)).join(UNFILLED);

  return filled + (middle ? middle : '') + unfilled;
};
```

I was wondering if I could get some ideas on how to debug this myself and help!

Thanks.

**Comment by awitherow** [comment]
I managed to get it working by changing the default assignment of charlength:

```javascript
const progressBar = function(n, total, charLength = 10) {
```

**Comment by matryer** [comment]
Please submit a PR to fix the plugin?
