### ISSUE TITLE
re: SSH

### ISSUE THREAD

**Issue by iCarl** [matryer/bitbar-plugins#743]
FAO: (@thameera)
Is there an example config file for SSH?

**Comment by thameera** [comment]
The plugin just looks for the lines starting with `Host` in the config file. Here's an example config:

```
Host baprod
HostName 128.189.31.70
User tham

Host md
HostName 139.59.17.121
User thameera
IdentityFile "~/.ssh/md-prd.pem"
```

**Comment by iCarl** [comment]
Thanks!
