### ISSUE TITLE
re: Screenshotter

### ISSUE THREAD

**Issue by Scellow** [matryer/bitbar-plugins#745]
Hello,

This plugin seems to be broken, it can take screenshots and save them on disk, but the following doesn't:

* Upload to imgur doesn't work
* Open Screenshot folder doesn't work

OS: macOS 10.12

Plugin: https://getbitbar.com/plugins/System/Screenshotter.1d.sh

**Comment by tresni** [comment]
Upload to imgur requires a 3rd party utility named `imgur_uploader` be installed in your `$PATH`.  Looks like it might expect something like https://github.com/skorokithakis/imgur-uploader.

**Comment by matryer** [comment]
The past tense for "to screenshot" is "screenshat"

**Comment by Scellow** [comment]
I'll test that, thanks guys
