### ISSUE TITLE
launch path is not accesible

### ISSUE THREAD

**Issue by gregbenner** [matryer/bitbar-plugins#746]
Seems like all the javascript examples give a 'launch path is not accesible'
I'm using nvm for node js, could that be the issue?

**Comment by tresni** [comment]
Yes. Your node binary likely doesn't live where it's expected to by the script. In terminal do `which node` and replace the path in the first line of the plugin with the output of that command. 

-- Brian

**Comment by gregbenner** [comment]
Thanks! I found the error, needed a **chmod** on the plugin file. Sorry I didn't read that it's in the docs.

**Comment by notiv-nt** [comment]
https://github.com/matryer/bitbar#ensure-you-have-execution-rights

```
chmod +x plugin-file-name.sh
```
