### ISSUE TITLE
Ethereum provider

### ISSUE THREAD

**Issue by jvdmeij** [matryer/bitbar-plugins#758]
The Ethereum plugin calls https://coinmarketcap-nexuist.rhcloud.com/api/eth/price - which gives a proxy error. Therefore the extension is not working unfortunately.

**Comment by kristofferR** [comment]
`echo -n "Ξ="; curl -s "https://api.coinmarketcap.com/v1/ticker/ethereum/" | egrep -o '"price_usd": "[0-9]+(\.)?([0-9]{0,4}")?' | sed 's/"price_usd": //' | sed 's/\"//g'

I'm struggling with stripping the last numbers though.
