### ISSUE TITLE
re: Weather Underground

### ISSUE THREAD

**Issue by peha2407** [matryer/bitbar-plugins#763]
FAO: (@asnodgrass)
Hi Adam
I have a problem:
I want to put your Weather Underground Plugin on BitBar. I don't know why, but I get an error, telling me that the app can not load wunderground (see attached file). I have inserted the API, but it doesn't work. 
Could you please help me? I would be very grateful!
Yours,
Peter 

[Wunderground_BitBar_KST_oben.txt](https://github.com/matryer/bitbar-plugins/files/996874/Wunderground_BitBar_KST_oben.txt)

![bildschirmfoto 2017-05-12 um 15 44 27](https://cloud.githubusercontent.com/assets/6813170/26000898/df3dc1f4-372a-11e7-96d4-a6f1d4d63a86.png)

**Comment by asnodgrass** [comment]
Peter,

You have to also make sure the gem is installed, with `gem install
wunderground`. Please try that and see if it's happier.

Regards,
Adam

**Comment by peha2407** [comment]
Hi Adam
Thanks, I will try this on monday.
Regards,
Peter

---------------------------------
Von meinem iPad gesendet
Peter Haslebacher
Oberdorfstrasse 20
8416 Flaach
peter@haslebacher.com

> Am 12.05.2017 um 16:55 schrieb Adam Snodgrass <notifications@github.com>:
> 
> Peter,
> 
> You have to also make sure the gem is installed, with `gem install
> wunderground`. Please try that and see if it's happier.
> 
> Regards,
> Adam
>

**Comment by peha2407** [comment]
Hi Adam
Thanks, I have done the 'gem install wunderground' command. But now, I have one more problem: When I try to run the Wunderground Plugin, I get an error.
[Error_Wunderground.txt](https://github.com/matryer/bitbar-plugins/files/1000255/Error_Wunderground.txt)
Any idea?
Regards,
Peter

**Comment by asnodgrass** [comment]
Peter,

That looks like an error in the httparty gem. I'd try to downgrade to a
previous version, or consult with the authors of that gem. My local install
has 0.14.0 of httparty and has no issues.

Regards,
Adam

**Comment by peha2407** [comment]
Hi Adam

Thank you very much! It works now!
I have downgraded to 0.14.0 now, et voilà!

Regards,
Peter


> Am 15.05.2017 um 16:40 schrieb Adam Snodgrass <notifications@github.com>:
> 
> Peter,
> 
> That looks like an error in the httparty gem. I'd try to downgrade to a
> previous version, or consult with the authors of that gem. My local install
> has 0.14.0 of httparty and has no issues.
> 
> Regards,
> Adam
>

**Comment by peha2407** [comment]
Hi Adam,

One (hopefully) last question:
Entering my API_KEY and having set LOCATION to ‹autoip›, I get the weather of the station ID LSZH (Zurich Airport). We’ve got a weather station of our own: IZRICHZR8. How can I let your plugin show me this information?

Regards,
Peter


> Am 16.05.2017 um 09:23 schrieb Peter Haslebacher <peter@haslebacher.com>:
> 
> Hi Adam
> 
> Thank you very much! It works now!
> I have downgraded to 0.14.0 now, et voilà!
> 
> Regards,
> Peter
> 
> 
>> Am 15.05.2017 um 16:40 schrieb Adam Snodgrass <notifications@github.com <mailto:notifications@github.com>>:
>> 
>> Peter,
>> 
>> That looks like an error in the httparty gem. I'd try to downgrade to a
>> previous version, or consult with the authors of that gem. My local install
>> has 0.14.0 of httparty and has no issues.
>> 
>> Regards,
>> Adam
>>
