### ISSUE TITLE
re: Clipboard BASE64-Encoder

### ISSUE THREAD

**Issue by frakman1** [matryer/bitbar-plugins#799]
FAO: (@citoki)

I am not sure how this is supposed to work. I tried copying a selected png image in 'Preview' app. Then I selected the plugin to 'Encode Clipboard item with BASE64'. I saw the notification that it did that, but when I ran `echo `pbpaste`` in terminal, I got a blank line. 

Is this only supposed to encode text strings? How do I encode and display images using bitbar inside a plugin code?

**Comment by citoki** [comment]
Hi @frakman1 , sorry for the late reply. First of all, you're right, I intended that only text strings are converted with this tool. However you can encode image files with this command: `openssl base64 < ~/Downloads/image.jpg | tr -d '\n' | pbcopy`
