### ISSUE TITLE
re: Screenshotter

### ISSUE THREAD

**Issue by frakman1** [matryer/bitbar-plugins#800]
FAO: (@moshed)

This script fails due to `alerter` command not being found

![screenshotfail](https://user-images.githubusercontent.com/5826484/27521045-6571eafc-59e5-11e7-8a4c-5cbacf908d2e.png)

I downloaded the binary `alerter` from https://github.com/vjeantet/alerter/releases

I placed it in /usr/local/bin and can run it from the terminal:

```
$alerter
${EXECUTABLE_NAME} (1.0.0) is a command-line tool to send OS X User Notifications.

Usage: ${EXECUTABLE_NAME} -[message|list|remove] [VALUE|ID|ID] [options]
```

I've quit and restarted BitBat and refreshed the screenshotter script but it still complains about the command not being found.

Any ideas?

**Comment by moshed** [comment]
Would you mind showing me your script maybe we can debug it together.

**Comment by frakman1** [comment]
I don't have a script. I am just using the plugin directly. `Screenshotter.1d.sh` (see screenshot above)
I think bitbar just doesn't use `/usr/local/bin`

**Comment by tresni** [comment]
@frakman1 this is a known issue, bitbar is not guaranteed to get the correct `PATH` environemental variable due to a known OSX issue.  There is no current workaround with bitbar specifically, but you can edit scripts to point to the correct location of the utilities they use.

**Comment by frakman1** [comment]
Thanks you @tresni 
On a related issue, When I compile BitBar and run it from  XCode, I get an error when it tries to run 'top' from within my plugin script. However, it doesn't give me an error when I run it from the /Applications/... folder
The error is:

![image](https://user-images.githubusercontent.com/5826484/28507438-bc82f3fa-7000-11e7-99a9-70613fabce27.png)

Is this because XCode won't let you do certain things within the `/Users/username/Library/Developer/Xcode/DerivedData/BitBar-xxx/Build/Products/Debug/Frakalog.app/Contents/MacOS` folder?

Do you know of a workaround?
