### ISSUE TITLE
re: Check hosts

### ISSUE THREAD

**Issue by es-elektron** [matryer/bitbar-plugins#806]
FAO: (@christophschlosser)

Trying to run 'checkhosts.1m.go.txt' but I get "env: gorun: No such file or directory".

**Comment by christophschlosser** [comment]
Hey,

please try `gorun` from here: https://github.com/erning/gorun

Best
chris

**Comment by es-elektron** [comment]
How best to install this on OSX? I only see Ubuntu instructions.

**Comment by christophschlosser** [comment]
Hey,

could you try `go get github.com/erning/gorun`?

Best
chris

**Comment by MartinsIrbe** [comment]
Hey guys, didn't want to open a separate issue as I think this is exactly the same issue. I'm on macOS Sierra v10.12.5 and I'm using BitBar v1.9.2
I have installed `gorun` by running `go get github.com/erning/gorun`, it's installed correctly and I can execute the following script `test.1m.go`: 
```golang
#!/usr/bin/env gorun
package main

import (
    "fmt"
)

func main() {
    fmt.Println("hello friend")
}
```
When I run the script I get the expected output:
![image](https://user-images.githubusercontent.com/13367583/28242946-17d082f4-69b2-11e7-8e5e-3fb491c66292.png)

However, I'm seeing this in the bitbar:
![image](https://user-images.githubusercontent.com/13367583/28242942-edf61a66-69b1-11e7-90cd-2f92820e3273.png)

Can you please give an advice, what I'm doing wrong?

**Comment by MartinsIrbe** [comment]
I managed to get it woking by creating a bash script that runs `gorun` after exporting `PATH` with `GOPATH` before running it and pointing it to the test script like this:
```bash
#!/usr/bin/env bash

export GOPATH=$HOME/dev/go_workspace
export PATH=$HOME/bin:/usr/local/bin:$GOPATH/bin

gorun $HOME/dev/bitbar/test.1m.sh
```
Even though this is working, is there a way how to avoid creating a bash script, exporting GOPATH and PATH and then executing the scrip by giving the full path to the script? The other way is to create a valid go app, and then execute it by name after installing it.

**Comment by christophschlosser** [comment]
Actually you can run a compiled go program without an additional bash script, You just have to use the .cgo ending.
So the file should look something like this:
`checkhosts.1m.cgo`
