### ISSUE TITLE
re: Todoist Today

### ISSUE THREAD

**Issue by limacohen** [matryer/bitbar-plugins#835]
FAO: (@chiisaihayashi)

It shows an error when the API key is blank (logically) but when I fill it (with a valid one, checked on other integration) it hangs with a blank icon for a moment and then disappears.

**Comment by chiisaihayashi** [comment]
Hi,
Thanks to give that feedback.
Could I see the screenshots?

**Comment by limacohen** [comment]
Hi! Sorry it took me so long to reply. I'm attaching the menubar icon and Terminal output.
Thank you, cheers!

![screen shot 2017-09-04 at 4 07 24 pm](https://user-images.githubusercontent.com/541169/30036640-97ccf3c4-918b-11e7-94b3-86e2377da108.png)
![screen shot 2017-09-04 at 4 08 13 pm](https://user-images.githubusercontent.com/541169/30036644-9cf9bea4-918b-11e7-83df-b9fa3eab878f.png)

**Comment by limacohen** [comment]
I'm deeply sorry, I got all mixed up since I had issues with both plugins. Here's the screenshot, no Terminal output whatsoever though.

![screen shot 2017-09-11 at 4 23 04 am](https://user-images.githubusercontent.com/541169/30262898-2cec6062-96a9-11e7-817e-0bea58fd26a8.png)

**Comment by kobayashi** [comment]
Could you let me know which python version use?

**Comment by limacohen** [comment]
I actually tried it with every version in my system and got different error messages. Then suddenly, it was working. Running Python 2.7.12 now. Thanks!

**Comment by nrishoj** [comment]
Hi guys,

I get the same error:

```bash
Traceback (most recent call last):
  File "[...]/bitbar-enabled/todoist.1m.py", line 12, in <module>
    import urllib, urllib2
ModuleNotFoundError: No module named 'urllib2'
$ python --version
Python 3.6.4 :: Anaconda, Inc.
$ 
```

Perhaps the plugin is only compatible with Python 2.x?

**Comment by kobayashi** [comment]
Hi,

PR #1045 makes it possible to support both python versions.
