### ISSUE TITLE
gfinance.5m.py stopped working

### ISSUE THREAD

**Issue by j-gao** [matryer/bitbar-plugins#842]
It seems Google's finance api stopped responding.
e.g. `http://finance.google.com/finance/info?client=ig&q=snap` is returning 404 now.

**Comment by djsmith42** [comment]
Looks like Google finally shut it down. They've been threatening to do this for a while. I'm trying to find a Yahoo-based replacement.

Reference: http://googlecode.blogspot.com.br/2011/05/spring-cleaning-for-some-of-our-apis.html

**Comment by tresni** [comment]
We recommend migrating to the Yahoo Finance tracker as the Google Finance API is deprecated.
