### ISSUE TITLE
re: Currency Tracker Transferwise

### ISSUE THREAD

**Issue by johnkyle510** [matryer/bitbar-plugins#846]
FAO: (@andrewzk)

Hello, I would like to change the currency from usd to thb thai baht. how do i do this?

**Comment by andrewzk** [comment]
Hi @johnkyle510 - to convert from USB to THB, set the `currency_from` and `currency_to` variables in `transferwise-currency-tracker.1m.py` as follows:

```
currency_from = 'USD'
currency_to = 'THB'
```
