### ISSUE TITLE
re: Countdown Timer -- How/where can I pass arguments?

### ISSUE THREAD

**Issue by danmandle** [matryer/bitbar-plugins#849]
I'm trying to run the [countdown](https://github.com/matryer/bitbar-plugins/blob/master/Time/countdown.1s.py) script. Looking at the source, it expects some command line arguments. I'm not seeing anywhere to pass those. I've done some fairly extensive looking around for this and the closest thing I can find is #88, but that is mostly about env vars. What am I missing here?

**Comment by tresni** [comment]
FOA: @Furkanzmc

**Comment by Furkanzmc** [comment]
Hi @danmandle.

You can see the arguments documentation [https://github.com/matryer/bitbar-plugins/blob/1fa1eda490e6d63c95984ee2d991fbb75032a182/Time/countdown.1s.py#L34](here).

And here's an example:

```
countdown.py "--bar-title" "Custom Bar Title" "--no-cycle" "--date-format" "%d-%m-%Y" "Time #1" "17-07-2017" "Time #2" "15-08-2017"
```

**Comment by tresni** [comment]
I think the question is how you are getting that to show up in the bitbar menu.  Given Bitbar just looks for the file on disc and there is no way to pass command line params.  Are you just using a wrapper script?

**Comment by Furkanzmc** [comment]
Sorry. I misinterpreted the question. I personally use an `.sh` file that calls the main script with the appropriate arguments. If that's not a wanted behaviour with the community, I can quickly add the environment variable support.

**Comment by danmandle** [comment]
I don't think that environment variables would be appropriate for this application, but some documentation about needing the wrapping script sure would be helpful. As a new user there was no indication that it would be needed.

**Comment by Furkanzmc** [comment]
Sure thing. Thank you for pointing it out. I'll add it to the `<bitbar.desc>` tag and also to the `--help` parameter output.

**Comment by aurnik** [comment]
@Furkanzmc Do you have an example of your `.sh` file? I thought I had everything set up correctly and can see the time left in my terminal but not in my menubar.

**Comment by Furkanzmc** [comment]
I use the same as the oe in the help text.

```
chmod +x /Path/to/countdown.py && /Path/to/countdown.py "--bar-title" "Custom Bar Title" "--no-cycle" "--date-format" "%d-%m-%Y" "Time #1" "17-07-2017" "Time #2" "15-08-2017"
```
