### ISSUE TITLE
Vertical text?

### ISSUE THREAD

**Issue by Henrietta1989** [matryer/bitbar-plugins#855]
I have working script but i would like to show four digit number vertically to save menu space.

Now it shows:
1234

I would like to have:
1
2
3
4

**Comment by tresni** [comment]
If you want them to appear in the dropdown menu use three dashes:

```
Test
---
1
2
3
4
```

New lines are different entries.

**Comment by Henrietta1989** [comment]
Thanks but i want to see these numbers in menubar not in dropdown menu. This would save tons of space in menubar.

**Comment by tresni** [comment]
Not possible today and that would be something to bring up on the [matryer/bitbar](https://github.com/matryer/bitbar) issue tracker.
