### ISSUE TITLE
re: Weather/Wunderground - ruby problem

### ISSUE THREAD

**Issue by reteps** [matryer/bitbar-plugins#863]
It seems to be working through the command line, but when it's in my menu bar it gives me an error.
![image](https://user-images.githubusercontent.com/13869303/31035981-331b635a-a538-11e7-922a-d39c86c1f914.png)
![image](https://user-images.githubusercontent.com/13869303/31035994-44ae0e10-a538-11e7-98da-29e5cdcec87c.png)

**Comment by tresni** [comment]
Are you using rbenv or rvm?  Do you have the correct ruby gems installed in your system ruby?

**Comment by reteps** [comment]
I don't know. This is the environment: `#!/usr/bin/env ruby`. It shows that I have installed all the needed gems.

**Comment by tresni** [comment]
If you run that on the command line and you have rvm, rbenv, or ruby from homebrew/macports/etc, then you are getting something totally different then system installed ruby.

Try this:

```sh
$ which ruby
$ /usr/bin/gem list
```

`which ruby` should tell you the path to your ruby binary.  If it doesn't say `/usr/bin/ruby`, you aren't using the system installed ruby.

`/usr/bin/gem list` should tell you the system installed gems.  If it doesn't show wunderground, then try doing `/usr/bin/gem install wunderground` and see if that resolves your issue.

**Comment by reteps** [comment]
got it. The gem was installed for `/usr/local/bin/gem` not `usr/bin/gem`.
