### ISSUE TITLE
Unrelated Menu Bar Icons Moving Back and Forth…

### ISSUE THREAD

**Issue by faxotherapy** [matryer/bitbar-plugins#87]
Just sitting on the left side of my BitBar are a group of icons moving back and forts. For example, sitting just on the left side of BitBar-related simple weather script are my f.lux icon. The latter moves half a quater inch towards the left, then revert back to its original position. It does this indefinitely. It happens for any script.

**Comment by matryer** [comment]
Can you 'ls' the contents of your plugin directory?

**Comment by faxotherapy** [comment]
```
ls -lh /usr/local/etc/BitBar
total 48
-rwxr-xr-x@ 1 Nath  admin   771B 10 jan 22:51 DNS_Status.1m.sh
-rwxr-xr--@ 1 Nath  admin   484B 10 jan 22:47 HTTPS_Port_Status.1m.sh
-rwxr-xr-x@ 1 Nath  admin   416B  9 jan 13:13 IP.1m.sh
-rwxr-xr-x@ 1 Nath  admin   3,7K 11 jan 12:36 Privoxy_Status.5s.sh
-rwxr-xr-x@ 1 Nath  admin   1,2K 10 jan 21:55 Simple_Weather.15m.py
-rwxr-x---@ 1 Nath  staff    86B  9 jan 18:03 VPN_Check.3s.sh
```

**Comment by faxotherapy** [comment]
(in fact, its a move of a quater inch back and forth)

**Comment by matryer** [comment]
Could you do before/after screenshots? Cannot reproduce this.

**Comment by faxotherapy** [comment]
Dear Sir,

thanks for your interest in attempting to resolve this issue. Please, 
find attached gif.

"Clouds" and Privoxy icons are from BitBar. Then, you will recognize 
Adium and QuickTime screen-recorder icons on the left. They move back 
and forth.

Thanks for your help.

**Comment by faxotherapy** [comment]
![movingicons](https://cloud.githubusercontent.com/assets/6538008/12304518/d957aa06-ba27-11e5-832f-db755d13896d.gif)

**Comment by asnodgrass** [comment]
@faxotherapy I have seen similar behavior in version 1.3.1 when a file that could not be executed was present in the plugins folder.  It would only be noticeable when there were non-Bitbar icons in the menu bar to the left of Bitbar under those circumstances.  Make sure you can manually execute each plugin from your shell to isolate any issues.  I also recommend upgrading to [v1.4](https://github.com/matryer/bitbar/releases/tag/v1.4.0) if you aren't already there.

**Comment by matryer** [comment]
Great bug report - thanks. Does it do this continuously?

**Comment by matryer** [comment]
Some questions:

  * Is it possible that one of your scripts is producing non-output?
  * What if you run each script inside your Plugin folder in the terminal?
  * Do you see a BitBar menu for each plugin item?

**Comment by faxotherapy** [comment]
Yes, it does this continuously. You have asked two great questions! Your first and last question. Indeed, I have 6 ``sh`` scripts with no hidden files in the plugin directory:
```
★  ls -lah         
total 56
drwxr-xr-x   8 Nath  admin   272B 12 jan 15:51 .
drwxrwxr-x  18 Nath  admin   612B 13 jan 17:58 ..
-rwxr-xr-x@  1 Nath  staff   1,0K 13 jan 15:55 DNS_Status.1m.sh
-rwxr-xr-x@  1 Nath  staff   484B 10 jan 22:47 HTTPS_Port_Status.1m.sh
-rwxr-xr-x@  1 Nath  staff   466B 11 jan 20:23 IP.1m.sh
-rwxr-xr-x@  1 Nath  staff   4,5K 11 jan 19:27 Privoxy_Status.5s.sh
-rwxr-xr-x@  1 Nath  staff   140B 12 jan 15:16 Simple_Weather.15m.sh
-rwxr-xr-x@  1 Nath staff    86B  9 jan 18:03 VPN_Check.3s.sh
```
Only **two items** are permanently sitting on the menu bar:
* Privoxy from ``Privoxy_Status.5s.sh``
* Weather info (e.g., shown above by ``Clouds 5``) from ``Simple_Weather.15m.sh``

The other scripts make their output visible in the menu bar only when there is a non-regular event. For example, if I switch temporarily to a public DNS, rather than using my local caching DNS resolver, then a warning sign followed by the word DNS will show up. 

When my VPN is down, then another icon should pop up in the menu bar.

Thank your for your support.

**Comment by faxotherapy** [comment]
Also, a bit strange is that there is now a large space between the VPN and Rain icons. Both issued by BitBar.

**Comment by faxotherapy** [comment]
![menuicon_issue](https://cloud.githubusercontent.com/assets/6538008/12320038/265f6048-ba9e-11e5-9ad6-ce87c6369898.gif)

**Comment by faxotherapy** [comment]
Above, all icons from BitBar (except Adium icon); TLS, DNS, VPN and IP icons only show up when there is something that I consider unusual.

**Comment by faxotherapy** [comment]
The reason why I want those icons to show up only when there is something unusual going on, it's to not clutter my menu bar with unnecessary icons when things are fine.

**Comment by faxotherapy** [comment]
Also, I must point out that I have to relaunch several times BitBar before it is actually launched.

BitBar version in use: 1.4

**Comment by faxotherapy** [comment]
One more thing. I tested all my scripts in Terminal and they all work fine.

**Comment by faxotherapy** [comment]
I confirm that when all icons are showing up at the same time, non-BitBar icons located on the left are no longer moving back and forth.

**Comment by matryer** [comment]
So it seems like it has something to do with plugins that yield no content. Do your plugins just output nothing and exit?

**Comment by matryer** [comment]
Have you ever run it in Xcode?

**Comment by faxotherapy** [comment]
Indeed. Plugins output an alert that remains on the menu bar so long there's no return to–what I consider–a normal situation. For example, if I keep using a public DNS, the ``DNS_Status`` script that is loaded every minute will continue to output the alert. As soon as I return to local DNS, the output disappears.

Maybe should I include an ``echo ""`` if ``situation returned to normal``?

I don't have Xcode installed on my system. Only the Command Line Tools…

**Comment by matryer** [comment]
Try the `echo ""` fix. This might be the first time someone has built a 'silent' plugin, so it's possible the BitBar app needs updating to support it (i.e. by properly hiding the menu bar item, rather than just display it with nothing in it)

**Comment by faxotherapy** [comment]
OK, I will try this. Thanks for confirming,

**Comment by faxotherapy** [comment]
Unfortunately, it has to be a non-blank character! No way to make it accept ``echo ""``; that is really too bad, making less interesting my use of BitBar.

**Comment by faxotherapy** [comment]
OK, the only thing that seems to work is echoing a backspace… Thus, the following if no “visible” output is preferred: ``echo -e  "b"`` or ``print "\b"``

**Comment by matryer** [comment]
Can you open an issue in matryer/bitbar project? If a plugin yields no output, the menu bar should be hidden.

**Comment by faxotherapy** [comment]
Yes, I can.

**Comment by faxotherapy** [comment]
Thank you both asnodgrass and matryer for helping me isolate the issue.
