### ISSUE TITLE
re: External IP country flag emoji

### ISSUE THREAD

**Issue by qimmiq** [matryer/bitbar-plugins#873]
FAO: (@MatzFan)
i get an always "connectin refused - connect (2). any ideas if smt is wrong on my end?

**Comment by MatzFan** [comment]
Please provide your system details; OS, proxy you use if any etc.

- What is the result of `curl http://ip-api.com` in Terminal?
- Does the plugin code work in irb?
- Do other bitbar network plugins work?

**Comment by qimmiq** [comment]
OS: El Capitan
Proxy: None 
VPN: frootvpn

Curl http://ip-api.com -> Connection refused (thats it i gues?!)
irb???
Yes other network Plugins work

**Comment by MatzFan** [comment]
I'm guessing your VPN IP address has been rate-limited by the API, as described in their [docs](http://ip-api.com/docs/). `curl http://ip-api.com/json` should give you something like this if so - see http://ip-api.com/docs/api:error_messages. Try the 'get my IP unbanned' link in the docs, or switch IP.
```
{"status": "fail","message": "QUOTA","query": "IP ADDRESS USED FOR QUERY"}  
```

**Comment by qimmiq** [comment]
it was sth else ... it just had to add www. and all done.

**Comment by qimmiq** [comment]
but i see why you chose ip-api.com :D mybe i switch back.
