### ISSUE TITLE
re: Weather Underground - Not working since High Sierra update

### ISSUE THREAD

**Issue by tukes2** [matryer/bitbar-plugins#926]
FAO: (@asnodgrass)
I love this BitBar WeatherUnderground plugin and have it on three machines for monitoring my weather station. But since I installed High Sierra (on all three), I can no longer get it to work. I tried several fixes I found online (updated Xcode, updated Ruby, etc.). But I cannot get it to work. I am not a coder and am way pout of my league here. Can you help me get this working again? This is the error I see:

From Terminal:
Last login: Thu Nov 30 12:28:49 on ttys001
/Users/Dan/Documents/BitBar/Wunderground.30m.rb
Dans-Mac-Pro:~ Dan$ /Users/Dan/Documents/BitBar/Wunderground.30m.rb
/Users/Dan/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- wunderground (LoadError)
	from /Users/Dan/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/Dan/Documents/BitBar/Wunderground.30m.rb:3:in `<main>'
Dans-Mac-Pro:~ Dan$ 

From BitBar in the Menu Bar:
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubyge…t/kernel_require.rb:55:in 'require':cannot load such file — underground (LoadError) from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubnygems/core_ext/kernel_require.rb:55:in 'require' from /Users/Dan/Documents/BitBar/Wunderground/30m.rb:3:in '<main>'

**Comment by reteps** [comment]
Full Error:
```
/Users/Dan/Documents/BitBar/Wunderground.30m.rb
/Users/Dan/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in require': cannot load such file -- wunderground (LoadError) from /Users/Dan/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:inrequire'
from /Users/Dan/Documents/BitBar/Wunderground.30m.rb:3:in
```
Error:
```cannot load such file -- wunderground (LoadError) from /Users/Dan/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in```

**Comment by asnodgrass** [comment]
@tukes2, this looks like it will have the same solution as #903. When you upgrade OS X, any gems you may have installed using the OS X-supplied Ruby will get removed, and must be readded.

**Comment by tukes2** [comment]
Thank you for that help. It fixed two of my three machines. But I am unable to repair the third — the one I was trying initially to fix myself. I'm pretty sure I fouled it up pretty badly with my updating of Ruby, I think I installed Homebrew, etc. I was feeling around in the dark, cluelessly.

Is there a way I can fully remove Ruby and all the background stuff to get a clean slate and start over again? I would think there is some code I can write into Terminal to do that, but I have no knowledge or experience with that. Going through the UI and Spotlight, I cannot find the files I see referenced in the code in Library or anywhere.

Thanks very much for the help.

**Comment by tukes2** [comment]
Small Update: If in the menu bar, I click the ! triangle, select Preferences, Refresh All, it does not work. I still have the ! triangle in the menu bar.

But if I click the ! triangle and select Run in Terminal, I get a new terminal window and the data all show successfully.

Any idea where my problem lies and how I can fix it? I have removed and reinstalled BitBar already, and that did not solve the issue.

**Comment by tukes2** [comment]
Maybe there is a way I can take the working setup on one of the other machines and copy it over to the one that is not working, overwriting what is there and getting it up and running? Just an idea.

**Comment by asnodgrass** [comment]
@tukes2 I missed this when I first replied (browsing Github from a smartphone is tricky), but I can see that you are using [RVM](https://rvm.io) to manage a Ruby installation. That means the specific instructions from #903 won't immediately aid you. You have a few options:

1. Install the `wunderground` plugin to your RVM-managed Ruby, using `gem install wunderground` without `sudo`. RVM manages a copy of Ruby owned entirely by your user account, so root privileges are not required to manage it.
2. Remove the RVM-managed Ruby (optionally, RVM as well) and just use the system Ruby; `sudo` will be required to add or remove gems as usual. Assuming RVM is functioning properly, the commands would first be `rvm list` to identify the name of the installed Ruby, followed by `rvm remove NAME`, where NAME is the name of the installed Ruby (usually something like ruby-1.2.3).

An advantage to option 1. above is that your Ruby (and the gem) should survive future OS updates, since it's stored within your home directory. Of course, if you don't develop in Ruby regularly, RVM could be considered an unnecessary extra.

I'd start with adding the gem to your RVM-managed Ruby, and see if everything behaves as you want/expect. If not, proceed to the removal of that Ruby (and/or RVM)

**Comment by tukes2** [comment]
#1 had no effect. It did install, but the menu bar still does not work.

#2 I started. I ran ram list and I see I have Ruby 2.4.1. When I look in the error when I run BitBar from the menu bar, I think I am seeing version 2.3.0 referenced. Is it possible that the issue is BitBar is just looking for the wrong version / copy of Ruby? I did not follow through with #2 beyond that point yet.

**Comment by asnodgrass** [comment]
The simplest answer here is probably going to be a full option 2 -- take off and nuke the entire site from orbit. Simply removing that Ruby from RVM should be enough, but you can thoroughly prune RVM from your system as well if you want to really be sure.

1. Removal of the RVM Ruby: as documented above. Confirm that you see the system Ruby by issuing `which ruby`, which should show you `/usr/bin/ruby`. Since RVM involves tinkering with your shell initialization files, Bitbar may not notice any changes until you log out and back in again.
    1. **Note**: If you see `/usr/local/bin/ruby` from the which command above, that probably indicates you've got [Homebrew](https://brew.sh) installed and a Ruby installed using that; I'll cover that next if needed.
2. Removal of RVM entirely:
    1. `mv $HOME/.rvm $HOME/delete-me-later` (this just renames the folder, which you can then later delete at your leisure using Finder as usual; in this way, you don't have to use a recursive `rm`, which can be dangerous if any mistakes are made)
    2. Remove RVM references from your shell initialization files. You can identify which files have been modified by issuing `grep -i rvm $HOME/.bash_profile $HOME/.bashrc $HOME/.profile`, and editing any that match. Any line in these files that starts with `#` is a comment, so you can also just prepend that character to any lines with RVM (case insensitive) as a starting point if you're worried about deletion.
        * **Note**: I'm assuming you're using the standard bash shell provided by OS X; if you aren't, you're own your own. 😄

**Comment by tukes2** [comment]
Here is what I did. Presently the Menu bar nor the Run in Terminal are working.

Last login: Fri Dec  1 10:56:51 on ttys000
Dans-Mac-Pro:~ Dan$ gem install wunderground
Fetching: wunderground-1.2.0.gem (100%)
Successfully installed wunderground-1.2.0
Parsing documentation for wunderground-1.2.0
Installing ri documentation for wunderground-1.2.0
Done installing documentation for wunderground after 0 seconds
1 gem installed
Dans-Mac-Pro:~ Dan$ rvm list

rvm rubies

=* ruby-2.4.1 [ x86_64 ]

# => - current
# =* - current && default
#  * - default

Dans-Mac-Pro:~ Dan$ which ruby
/Users/Dan/.rvm/rubies/ruby-2.4.1/bin/ruby
Dans-Mac-Pro:~ Dan$ rvm remove ruby-2.4.1
ruby-2.4.1 - #removing src/ruby-2.4.1..
ruby-2.4.1 - #removing rubies/ruby-2.4.1.......................................|
Error running '__rvm_rm_rf /Users/Dan/.rvm/rubies/ruby-2.4.1',
please read /Users/Dan/.rvm/log/1512147036_ruby-2.4.1/remove.rubies.log
Using /Users/Dan/.rvm/gems/ruby-2.4.1
Dans-Mac-Pro:~ Dan$ rvm list

rvm rubies

=* ruby-2.4.1 [ missing bin/ruby ]

# => - current
# =* - current && default
#  * - default

Dans-Mac-Pro:~ Dan$ which ruby
/usr/bin/ruby
Dans-Mac-Pro:~ Dan$ mv $HOME/.rvm $HOME/delete-me-later
Dans-Mac-Pro:~ Dan$ grep -i rvm $HOME/.bash_profile $HOME/.bashrc $HOME/.profile
/Users/Dan/.bash_profile:[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
/Users/Dan/.bashrc:# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
/Users/Dan/.bashrc:export PATH="$PATH:$HOME/.rvm/bin"
/Users/Dan/.profile:# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
/Users/Dan/.profile:export PATH="$PATH:$HOME/.rvm/bin"
/Users/Dan/.profile:[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
Dans-Mac-Pro:~ Dan$ gem install wunderground
Fetching: public_suffix-3.0.1.gem (100%)
Successfully installed public_suffix-3.0.1
Fetching: addressable-2.5.2.gem (100%)
Successfully installed addressable-2.5.2
Fetching: multi_xml-0.6.0.gem (100%)
Successfully installed multi_xml-0.6.0
Fetching: httparty-0.15.6.gem (100%)
When you HTTParty, you must party hard!
Successfully installed httparty-0.15.6
Fetching: wunderground-1.2.0.gem (100%)
Successfully installed wunderground-1.2.0
Parsing documentation for public_suffix-3.0.1
Installing ri documentation for public_suffix-3.0.1
Parsing documentation for addressable-2.5.2
Installing ri documentation for addressable-2.5.2
Parsing documentation for multi_xml-0.6.0
Installing ri documentation for multi_xml-0.6.0
Parsing documentation for httparty-0.15.6
Installing ri documentation for httparty-0.15.6
Parsing documentation for wunderground-1.2.0
Installing ri documentation for wunderground-1.2.0
Done installing documentation for public_suffix, addressable, multi_xml, httparty, wunderground after 3 seconds
5 gems installed
Dans-Mac-Pro:~ Dan$

**Comment by tukes2** [comment]
I do have a remove.rubies.log file. It is pretty big, though, so I did not paste it in here.

**Comment by tukes2** [comment]
[remove.rubies.log](https://github.com/matryer/bitbar-plugins/files/1522304/remove.rubies.log)

**Comment by tukes2** [comment]
Did a restart and then tried to install wonder ground gem — with and without sudo. Got this:

Last login: Fri Dec  1 12:04:04 on console
Restored session: Fri Dec  1 12:03:06 EST 2017
Dans-Mac-Pro:~ Dan$ sudo gem install wonderground
Password:
ERROR:  Could not find a valid gem 'wonderground' (>= 0) in any repository
gem install wondergroundERROR:  Possible alternatives: wunderground, rb_wunderground, wunderground-api, wunderground_api, undergrounder
Dans-Mac-Pro:~ Dan$ gem install wonderground
ERROR:  Could not find a valid gem 'wonderground' (>= 0) in any repository
ERROR:  Possible alternatives: wunderground, rb_wunderground, wunderground-api, wunderground_api, undergrounder
Dans-Mac-Pro:~ Dan$

**Comment by tukes2** [comment]
I see I had a dumb typo. Fixed that, installed wUnderground and all is working again. THANK YOU SO MUCH FOR YOUR HELP! Very much appreciated.

**Comment by asnodgrass** [comment]
@tukes2 Glad to hear you got it worked out!
