### ISSUE TITLE
re: Slack Notification

### ISSUE THREAD

**Issue by pixelrogue1** [matryer/bitbar-plugins#936]
FAO: (@mgjo5899)

After installation (High Sierra), a warning symbol is displayed in the menubar, with the message "You need to 'pip install requests'.

<img width="246" alt="screen shot 2017-12-07 at 1 05 23 pm" src="https://user-images.githubusercontent.com/34347975/33730869-50bdd83c-db4f-11e7-9132-5b53458e106e.png">

**Comment by mgjo5899** [comment]
The slack notification uses requests module of your chosen python.  You can install requests module by 'pip install requests'

**Comment by pixelrogue1** [comment]
I am just a slack user seeking a menu bar notification as to not miss messages. No python etc.

**Comment by mgjo5899** [comment]
Oh... Um even though you install requests, it would require you to put down channel developer's keys for you to be able to use Slack APIs.  I also tried to find a menu bar notification but I could not find one.  I will try to find a better solution!

**Comment by recet** [comment]
Any solutions for this yet?

**Comment by legshort** [comment]
Although I have installed the `requests` package, the error keeps display to `install pip requests`.

**Comment by mgjo5899** [comment]
@legshort Have you tried checking whether your system python is the one that you've installed requests package?

**Comment by pixelrogue1** [comment]
I sm just casual user - know nothing about python servers etc.

**Comment by mgjo5899** [comment]
@pixelrogue1 @recet  Had little time over holidays.  I am investigating a better way of dealing with this notification.  A contribution is open to whoever is interested in working on it!  :)

**Comment by legshort** [comment]
@mgjo5899 I was confused with my `pyenv` setting, `requests` is installed properly, however, I'm waiting for an organization to confirm my personal slack token.
Even though, it was my bad, thanks for your help.

**Comment by stavfx** [comment]
Going through the Wavebox app repo, I came across an undocumented api method (`https://slack.com/api/users.counts`) that might help you get all the data you need with 1 call.
Saw it here:
https://github.com/wavebox/waveboxapp/blob/d1ef5d14132fc8722e8762b777a8cd982dd0aaf0/src/scenes/mailboxes/src/stores/slack/SlackHTTP.js#L84

**Comment by gnaihc** [comment]
After install requests, it runs fine in Terminal. However, the menu bar still shows the `You need to pip install requests` error. How do I solve this?

**Comment by mgjo5899** [comment]
@gnaihc I would check whether the python you ran in the terminal is the same one as what the file is running upon.  Would you check that out from the top of the file and do `which python` to verify they are the same ones?

**Comment by gnaihc** [comment]
Got it. Found the right version and the issue is fixed. Thanks!
