### ISSUE TITLE
re: Live Tennis Scores

### ISSUE THREAD

**Issue by mn113** [matryer/bitbar-plugins#959]
FAO: (@anupsabraham)

This plugin errors, I think ATP changed their API response format a little. The score of an unstarted set is now returned as an empty string.

http://www.atpworldtour.com/en/-/ajax/Scores/GetInitialScores

You can fix it by changing the condition on line 49 to:

```python
if set_name in match[team_name]['Scores'] \
and len(match[team_name]['Scores'][set_name]) > 0:
```

So essentially by changing the test from `!= nbsp` to `len() > 0`.

**Comment by anupsabraham** [comment]
Oh. I had seen this issue in my system. And updated my code. But forgot to update the repo and push a commit. Will do that right now. Thanks for reporting this issue and using this plugin. 😀
