### ISSUE TITLE
re: Jenkins All Build Status

### ISSUE THREAD

**Issue by 1ak31sha** [matryer/bitbar-plugins#966]
Hi, i just installed the Jenkins plugin, but by default it shows yellow caution sign, and an error on line 12: requests module not found. I think its a bug?

Do i need to configure this file for it to work or should it show something out of the box?

FAO: (@drassi)

**Comment by drassi** [comment]
Hey, yes this script actually requires the python "requests" module to run properly. You can just "pip install requests", or sudo it if you're installing it systemwide.
