### ISSUE TITLE
re: Slack Notification error

### ISSUE THREAD

**Issue by dingo-d** [matryer/bitbar-plugins#971]
FAO: (@mgjo5899)

Hi!

Upon installation, I got this error (after installing the `request` package)

![screen shot 2018-01-31 at 09 28 31](https://user-images.githubusercontent.com/8638515/35612481-3375f0b2-0669-11e8-8b20-3809dc763167.png)

```sh
/Users/user/BitBarPlugins/slack-unread.1s.py
Traceback (most recent call last):
  File "/Users/user/BitBarPlugins/slack-unread.1s.py", line 53, in <module>
    results = pool.map(get_channel_list, tokens)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
KeyError: 'channels'
```

Any ideas what is wrong?

**Comment by mgjo5899** [comment]
@dingo-d Did you try putting in your workspace tokens into the file?

**Comment by dingo-d** [comment]
No, I just installed the plugin, thought it will do that on its own...

**Comment by mgjo5899** [comment]
Currently, you have to create tokens for each of your workspace and put them into the tokens part of the code.  I am trying to change it to something similar to what we see on our initial login to workspaces in the Slack client program.

**Comment by scottkoons** [comment]
@mgjo5899 I'm new to the BitBar and Slack for that matter.  This is prob a dumb question, but where do I find my workspace tokens and where do I put it in the py code?  Thanks.
