### ISSUE TITLE
re: Cycle text and detail text

### ISSUE THREAD

**Issue by atomchind** [matryer/bitbar-plugins#973]
FAO: (@matryer)

Hi there, I hope you're still open for questions or help
I just stumbled across the BitBar and it's plugins. It's awesome!
I'm using the cycle through text plugin and I'm ran in some problems with it.
It seems that the numbers of echo's is limited, it's repeating after a while (even if it hasn't reached the end). Any way to increase the amount? 

Also, I would like to ask you, if there's any letters or characters that aren't supported? 

Below, the content of the plugin.sh-file
`echo Protektionismus: Alle Massnahmen des Staates 
echo die getroffen werden, um inländische Wirtschaft
echo vor ausländischen Konkurrenz zu schützen
echo Formen Protektionismus: Einfuhrzölle, Kontingente, 
echo Subventionierung, Richtlinien, Vorschriften
echo Hauptanl WTO: freier Warenverkehr,durch Beseitigung Handelsbarrieren
echo Handelspartn der Schweiz für Ex- und Import
echo Exp/Imp Deutschland, USA, Grossbritannien, China/Italien, HongKong/Frankreich
echo Entwicklungsg Import-, Exportwerte: Aufschwungsphase, Wirschaftsindikatoren Wachstum, Beschäftigungsquote höher
echo Saldo Handelsbilanz Schweiz 2016: 32 Mrd, mit Überschuss
echo BIP Schweiz 2016: CHF 650 Mrd: 46% Exportanteil
echo ende
echo Fix Wechselk Staat legt ein festes Umtauschverh zu anderen Währung fest
echo Kalkulierbar,vorhersehbar, geringe Transaktionsk, Glaubwürdigkeit Wirtschaft
echo keine Autonomität der Geldpolitik, Auf-/Abwertung nicht mehr möglich
echo Flex Wechselk Angebot und Nachfrage frei Devisenmärkten
echo eigene Geldpolitik, Wettbewerbsfähigkeit erhöhen, NB muss nicht intervenieren um Kurs zu halten
echo Unsicherheit der Unternehmen, mehr Umkosten`

**Comment by tresni** [comment]
This should be reported on matryer/bitbar as it's related to the core program and not a specific plugin.
