### ISSUE TITLE
re: Weather

### ISSUE THREAD

**Issue by rdcosta** [matryer/bitbar-plugins#98]
FAO: (@seripap)

I get the following error when I try and use your BitBar plugin
  File "weather.15m.py", line 94
    'city': str(location["city"]),
         ^
SyntaxError: invalid syntax

Thanks

**Comment by pvledoux** [comment]
Same problem here.

**Comment by matryer** [comment]
Does anyone know how to fix this?

**Comment by keithamus** [comment]
I suppose you're using the ForecastIO one? It looks like [this line](https://github.com/matryer/bitbar-plugins/blob/21773f78eb0aa1327d1387014540c37b5b6f6ddb/Weather/ForecastIO/weather.15m.py#L92) is missing a trailing comma.

**Comment by keithamus** [comment]
That was my bad, I merged in this PR which caused it: https://github.com/matryer/bitbar-plugins/pull/80

**Comment by seripap** [comment]
#103 should resolve

**Comment by rdcosta** [comment]
Thanks for the quick response - that fixed it
