### ISSUE TITLE
re: Cryptocurrency Prices

### ISSUE THREAD

**Issue by SeepSoak** [matryer/bitbar-plugins#980]
FAO: (@viiraj)

Hey there. Bitcoin price isn't working from Coinbase. It shows empty for me, here's a screenshot.

<img width="205" alt="image" src="https://user-images.githubusercontent.com/23070927/36347859-636ba314-1417-11e8-96bb-282feee374d2.png">

**Comment by viiraj** [comment]
Thanks for this. I have just submitted PR #981 based on a change I made to my local copy of the script after the Coinbase API changed.

You can go ahead and copy/paste the changed code from that PR - I’ve been using this on my machine for several weeks now and it works fine.
