### ISSUE TITLE
re: Metar

### ISSUE THREAD

**Issue by DirkLorenz** [matryer/bitbar-plugins#993]
FAO: (@parabuzzle)

Hallo,

bitbar funktioniert auf meinem IMAC schon lange (High Sierra 10.13.3)
nun wollte ich Metar nutzen und erhalte folgende Fehlermeldung.
/metar.5m.rb
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bitbar (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'

Fehlt ein Suchpfad?

Gruß Dirk

**Comment by parabuzzle** [comment]
Hallo,

Es scheint, dass Sie ein `gem install bitbar` tun müssen. Wenn Sie einfach die `metar.5m.rb` in der Befehlszeile ausführen, funktioniert es oder Fehler auf die gleiche Weise?

Entschuldige meinen schlechten Deutsch

-Mike

**Comment by DirkLorenz** [comment]
Hallo,

Danke für das schnelle Feedback.
nach Ausführung von  gem install bitbar kommt folgender Fehler

/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- metar (LoadError)

sowohl beim ausführen auf Kommandozeile ls auch in bitbar.

Viele Grüße

Dirk

**Comment by parabuzzle** [comment]
Ok, es sieht so aus, als müssten Sie den Rest der benötigten Bibliotheken in Ihrem System Ruby installiert haben. Mach einfach folgendes: `gem install inifile metar-parser`

Dann probier es aus.

-Mike

**Comment by DirkLorenz** [comment]
Hallo,  
wieder einen Schritt weiter, jetzt kommt die Meldung:

host:~ user$ ..../scripts/metar.5m.rb
......../scripts/metar.5m.rb:56:in `airport_code': undefined method `[]' for nil:NilClass (NoMethodError)
	from ........./scripts/metar.5m.rb:137:in `<main>'
host:~ user$ 

Dirk

**Comment by parabuzzle** [comment]
Es scheint, dass Sie die erforderliche Konfiguration vermissen. Bitte folgen Sie den Installationsanweisungen im Repository des Plugins.

In der Datei ~ / .bitbarrc legen Sie den Flughafencode fest, den Sie sehen möchten:

```
[metar]
airport=KDPA
```

https://github.com/parabuzzle/bitbar_metar#setup
